#!/usr/bin/env python3
#
# Copyright: © 2021 Netdata Inc.
# SPDX-License-Identifier: GPL-3.0-or-later
'''Generate the `Makefile.am` for the dashboard directory.'''

import sys

from pathlib import Path

BASEPATH = Path(sys.argv[1])

TEMPLATE = '''
# Auto-generated by generate-dashboard-makefile.py
# Copyright: © 2021 Netdata Inc.
# SPDX-License-Identifier: GPL-3.0-or-later
MAINTAINERCLEANFILES = $(srcdir)/Makefile.in

dist_noinst_DATA = \\
    README.md

dist_web_DATA = \\
    {0} \\
    $(NULL)

webcssdir=$(webdir)/css
dist_webcss_DATA = \\
    {1} \\
    $(NULL)

webfontsdir=$(webdir)/fonts
dist_webfonts_DATA = \\
    {2} \\
    $(NULL)

webimagesdir=$(webdir)/images
dist_webimages_DATA = \\
    {3} \\
    $(NULL)

weblibdir=$(webdir)/lib
dist_weblib_DATA = \\
    {4} \\
    $(NULL)

webstaticcssdir=$(webdir)/static/css
dist_webstaticcss_DATA = \\
    {5} \\
    $(NULL)

webstaticjsdir=$(webdir)/static/js
dist_webstaticjs_DATA = \\
    {6} \\
    $(NULL)

webstaticmediadir=$(webdir)/static/media
dist_webstaticmedia_DATA = \\
    {7} \\
    $(NULL)
'''


def genfilelist(path):
    '''Generate a list of files for the Makefile.'''
    files = [f for f in path.iterdir() if f.is_file() and f.name != 'README.md']
    files = [Path(*f.parts[1:]) for f in files]
    return ' \\\n    '.join([str(f) for f in files])


MAKEFILEDATA = TEMPLATE.format(
    genfilelist(BASEPATH),
    genfilelist(BASEPATH.joinpath('css')),
    genfilelist(BASEPATH.joinpath('fonts')),
    genfilelist(BASEPATH.joinpath('images')),
    genfilelist(BASEPATH.joinpath('lib')),
    genfilelist(BASEPATH.joinpath('static', 'css')),
    genfilelist(BASEPATH.joinpath('static', 'js')),
    genfilelist(BASEPATH.joinpath('static', 'media')),
)

BASEPATH.joinpath('Makefile.am').write_text(MAKEFILEDATA)
