// SPDX-License-Identifier: GPL-3.0-or-later

package db2

const (
	queryDetectVersionLUW = `SELECT SERVICE_LEVEL, HOST_NAME, INST_NAME FROM SYSIBMADM.ENV_INST_INFO`
	queryDetectVersionI = `SELECT 'DB2 for i' FROM SYSIBM.SYSDUMMY1`

	queryGlobalConnections = `
		SELECT 
			COUNT(*) as TOTAL_CONNS,
			SUM(CASE WHEN APPL_STATUS = 'CONNECTED' THEN 1 ELSE 0 END) as ACTIVE_CONNS,
			SUM(CASE WHEN APPL_STATUS = 'UOWEXEC' THEN 1 ELSE 0 END) as EXECUTING_CONNS
		FROM SYSIBMADM.APPLICATIONS
	`
	queryGlobalConnectionsSimple = `SELECT COUNT(*) FROM SYSIBMADM.APPLICATIONS`

	queryLockMetrics = `
		SELECT 
			LOCK_WAITS,
			LOCK_TIMEOUTS,
			DEADLOCKS,
			LOCK_ESCALS,
			TOTAL_SORTS,
			SORT_OVERFLOWS,
			ROWS_READ,
			ROWS_MODIFIED
		FROM SYSIBMADM.SNAPDB
	`

	queryBufferpoolAggregateMetrics = `
		SELECT 
			CASE 
				WHEN (POOL_DATA_L_READS + POOL_INDEX_L_READS) > 0 
				THEN ((POOL_DATA_LBP_PAGES_FOUND + POOL_INDEX_LBP_PAGES_FOUND) * 100) / 
				     (POOL_DATA_L_READS + POOL_INDEX_L_READS)
				ELSE 100 
			END as HIT_RATIO
		FROM SYSIBMADM.SNAPBP
	`

	queryLogSpaceMetrics = `
		SELECT 
			TOTAL_LOG_USED,
			TOTAL_LOG_AVAILABLE
		FROM SYSIBMADM.LOG_UTILIZATION
	`

	queryLongRunningQueries = `
		SELECT 
			COUNT(*) as TOTAL_COUNT,
			SUM(CASE WHEN ELAPSED_TIME_MIN >= 5 AND ELAPSED_TIME_MIN < 15 THEN 1 ELSE 0 END) as WARNING_COUNT,
			SUM(CASE WHEN ELAPSED_TIME_MIN >= 15 THEN 1 ELSE 0 END) as CRITICAL_COUNT
		FROM SYSIBMADM.LONG_RUNNING_SQL
		WHERE ELAPSED_TIME_MIN > 0
	`

	queryBackupStatus = `
		SELECT 
			OPERATION,
			START_TIME,
			OPERATIONTYPE,
			SQLCODE
		FROM SYSIBMADM.DB_HISTORY
		WHERE OPERATION = 'B'
		  AND START_TIME >= CURRENT TIMESTAMP - %d DAYS
		ORDER BY START_TIME DESC
		FETCH FIRST 10 ROWS ONLY
	`
	queryBackupStatusSimple = `
		SELECT 
			MAX(START_TIME) as LAST_BACKUP
		FROM SYSIBMADM.DB_HISTORY
		WHERE OPERATION = 'B' AND SQLCODE = 0
	`

	queryDatabaseInstances = `
		SELECT 
			DB_NAME,
			DB_STATUS,
			APPLS_CUR_CONS
		FROM SYSIBMADM.SNAPDB
		FETCH FIRST %d ROWS ONLY
	`

	queryBufferpoolInstances = `
		SELECT 
			BP_NAME,
			POOL_DATA_L_READS + POOL_INDEX_L_READS as TOTAL_READS,
			POOL_DATA_P_READS + POOL_INDEX_P_READS as TOTAL_WRITES,
			CASE 
				WHEN (POOL_DATA_L_READS + POOL_INDEX_L_READS) > 0 
				THEN ((POOL_DATA_LBP_PAGES_FOUND + POOL_INDEX_LBP_PAGES_FOUND) * 100) / 
				     (POOL_DATA_L_READS + POOL_INDEX_L_READS)
				ELSE 100 
			END as HIT_RATIO,
			PAGESIZE,
			NPAGES,
			NPAGES - FREE_PAGES as USED_PAGES
		FROM SYSIBMADM.SNAPBP
		FETCH FIRST %d ROWS ONLY
	`

	queryTablespaceInstances = `
		SELECT 
			TBSP_NAME,
			TBSP_TYPE,
			TBSP_CONTENT_TYPE,
			TBSP_STATE,
			TBSP_TOTAL_SIZE_KB,
			TBSP_USED_SIZE_KB,
			TBSP_FREE_SIZE_KB,
			CASE 
				WHEN TBSP_TOTAL_SIZE_KB > 0 
				THEN (TBSP_USED_SIZE_KB * 100) / TBSP_TOTAL_SIZE_KB
				ELSE 0 
			END as USED_PERCENT,
			TBSP_PAGE_SIZE
		FROM SYSIBMADM.TBSP_UTILIZATION
		WHERE TBSP_TYPE = 'DMS'
		ORDER BY TBSP_USED_SIZE_KB DESC
		FETCH FIRST %d ROWS ONLY
	`

	queryConnectionInstances = `
		SELECT 
			APPLICATION_ID,
			APPLICATION_NAME,
			CLIENT_HOSTNAME,
			SESSION_AUTH_ID,
			APPL_STATUS,
			UOW_COMP_STATUS,
			ROWS_READ,
			ROWS_WRITTEN,
			TOTAL_CPU_TIME
		FROM SYSIBMADM.APPLICATIONS
		WHERE APPL_STATUS IN ('CONNECTED', 'UOWEXEC')
		ORDER BY TOTAL_CPU_TIME DESC
		FETCH FIRST %d ROWS ONLY
	`

	queryTableInstances = `
		SELECT 
			TABSCHEMA,
			TABNAME,
			DATA_OBJECT_P_SIZE,
			INDEX_OBJECT_P_SIZE,
			LONG_OBJECT_P_SIZE,
			ROWS_READ,
			ROWS_WRITTEN
		FROM SYSIBMADM.ADMINTABINFO
		ORDER BY DATA_OBJECT_P_SIZE DESC
		FETCH FIRST %d ROWS ONLY
	`

	queryIndexInstances = `
		SELECT
			INDSCHEMA,
			INDNAME,
			NLEAF,
			INDEX_SCANS,
			FULL_SCANS
		FROM SYSCAT.INDEXES
		ORDER BY NLEAF DESC
		FETCH FIRST %d ROWS ONLY
	`
)
