#!/bin/sh

set -e

case "$1" in
  configure|reconfigure)
    chown root:netdata /usr/libexec/netdata/plugins.d/logs-management.plugin
    chmod 0750 /usr/libexec/netdata/plugins.d/logs-management.plugin
    if ! setcap "cap_dac_read_search=eip cap_syslog=eip" /usr/libexec/netdata/plugins.d/logs-management.plugin; then
        chmod -f 4750 /usr/libexec/netdata/plugins.d/logs-management.plugin
    fi
    ;;
esac

#DEBHELPER#

exit 0
