// dead_code is silenced because the vocabulary declared here is not fully
// exercised: e.g. `Command::EmptyLine` and `Error::MalformedLine` are never
// constructed.
#![allow(dead_code)]

//! Byte-level framing for the pluginsd line protocol between a plugin and the
//! Netdata agent over stdin/stdout: splits a buffer into one line or one
//! payload block at a time, resolves the first word against the keyword
//! table, and returns the command with the raw, unparsed remainder of the
//! line.
//!
//! Bottom layer of the crate's three parsing stages: [`LineParser`] here feeds
//! `message_parser::MessageParser` (turns `Command`s into `Message`s), which
//! `tokio_codec` exposes as `tokio_util::codec` `Decoder`/`Encoder` impls. The
//! module is crate-private; outside users only see `Message` and the transport
//! types re-exported from `lib.rs`.
//!
//! Framing shared with the agent side (`src/plugins.d/pluginsd_parser.c`,
//! keyword table `src/plugins.d/gperf-hashtable.h`):
//!
//! - One command per line, terminated by `\n`; a `\r` before it is not
//!   stripped and stays part of the line content.
//! - Empty and all-whitespace lines yield `ParsedLine { command: None, .. }`.
//! - The keyword is the first word, looked up byte-exact in the `COMMAND_MAP`
//!   generated by `build.rs`. `word_iterator::WordIterator` splits only on
//!   `' '` and `'\t'`, while the C agent's `isspace_map_pluginsd` also splits
//!   on `\r`, `\f`, `\v` and `=`. Words not in the map become
//!   [`Command::Unknown`]; keywords in the map without a match arm panic (see
//!   `Token`).
//! - Payload blocks (`FUNCTION_RESULT_BEGIN`..`FUNCTION_RESULT_END`,
//!   `FUNCTION_PAYLOAD`..`FUNCTION_PAYLOAD_END`, `JSON`..`JSON_PAYLOAD_END`)
//!   are deferred: the body lines bypass keyword lookup until a line exactly
//!   equal to the end marker, then the whole block is returned as one chunk
//!   (see [`ParserState`]).
//!
//! The C agent parser ends a deferred block on any line whose first keyword
//! matches (`find_first_keyword` in `pluginsd_parser.h`) and aborts the
//! plugin above `PLUGINSD_MAX_DEFERRED_SIZE` (100 MiB, `libnetdata.h`); here
//! the marker must be the exact line and no size limit is enforced, so the
//! codec keeps the whole block buffered until the marker arrives.

use crate::word_iterator::WordIterator;

/// One variant per pluginsd keyword in the `COMMAND_MAP` generated by
/// `build.rs` (byte-exact keyword keys, mirroring the agent's table in
/// `src/plugins.d/gperf-hashtable.h`). Every map entry must have a match arm
/// in `parse_normal_line`: an entry without one makes any line carrying that
/// keyword panic. The variants without arms (`FLUSH`, `VARIABLE`, `LABEL`,
/// `CONFIG`, the host/replay/`DYNCFG_*` keywords, ...) declare the agent's
/// full vocabulary but are not consumed by this parser.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Token {
    Chart,
    ChartDefinitionEnd,
    Dimension,
    Begin,
    End,
    Set,
    Flush,
    Disable,
    Variable,
    Label,
    Overwrite,
    Clabel,
    ClabelCommit,
    Exit,
    Begin2,
    Set2,
    End2,
    HostDefine,
    HostDefineEnd,
    HostLabel,
    Host,
    ReplayChart,
    Rbegin,
    Rset,
    RdState,
    RsState,
    Rend,
    Function,
    FunctionResultBegin,
    FunctionResultEnd,
    FunctionPayloadBegin,
    FunctionPayloadEnd,
    FunctionCancel,
    FunctionProgress,
    Quit,
    Config,
    NodeId,
    ClaimedId,
    Json,
    JsonPayloadEnd,
    StreamPath,
    MlModel,
    TrustDurations,
    DynCfg,
    DynCfgRegisterModule,
    DynCfgRegisterJob,
    DynCfgReset,
    ReportJobStatus,
    DeleteJob,
}

// Generated by build.rs into $OUT_DIR/tokens.rs:
// static COMMAND_MAP: phf::Map<&'static [u8], Token>
include!(concat!(env!("OUT_DIR"), "/tokens.rs"));

/// Result alias for parser operations; `parse` itself only ever returns
/// [`Error::IncompleteLine`].
pub type Result<T> = core::result::Result<T, Error>;

/// Parser errors
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Error {
    /// No complete line yet — no `\n` in normal mode, or no end-marker line
    /// inside a payload block. Not fatal: `tokio_codec::Decoder` treats this
    /// as "need more input" and keeps the buffer.
    IncompleteLine,
    /// Declared but never produced by this parser.
    MalformedLine,
    /// Underlying stream I/O failure, arrived as `std::io::Error` and
    /// converted by [`Error::from`].
    Io,
}

// `tokio_util::codec` converts underlying stream I/O errors into the
// decoder's error type via `From<io::Error>`, so `Error` must provide this
// conversion.
impl From<std::io::Error> for Error {
    fn from(_: std::io::Error) -> Self {
        Error::Io
    }
}

/// One pluginsd command line, borrowed from the input buffer (zero-copy):
/// `args` is the raw remainder of the line after the keyword — not split or
/// unquoted; `message_parser` re-parses it with `word_iterator::WordIterator`
/// per command. The enum covers the whole framing-layer vocabulary, but
/// `MessageParser::process_command` consumes only the function/payload/quit
/// subset and drops the rest: chart commands are recognized here and ignored
/// there (rt emits chart text as raw bytes via
/// `transport::MessageWriter::write_raw`, and the agent parses it — see
/// `src/plugins.d/pluginsd_parser.c`).
pub enum Command<'a> {
    // Chart definition commands
    Chart { args: &'a [u8] },
    Dimension { args: &'a [u8] },
    Variable { args: &'a [u8] },
    ChartDefinitionEnd,

    // Data update commands
    Begin { args: &'a [u8] },
    Set { args: &'a [u8] },
    End { args: &'a [u8] },

    // Function commands
    Function { args: &'a [u8] },
    /// Keyword `FUNCTION_PAYLOAD`: a call whose body follows as a payload
    /// block; opens the block.
    FunctionPayloadBegin { args: &'a [u8] },
    /// Keyword `FUNCTION_PAYLOAD_END` (the name lags the keyword it maps
    /// to); only reached outside an open block, since inside one the payload
    /// scanner consumes the marker line first.
    FunctionPayload { args: &'a [u8] },
    FunctionResultBegin { args: &'a [u8] },
    FunctionResultEnd { args: &'a [u8] },
    FunctionCancel { args: &'a [u8] },
    FunctionProgress { args: &'a [u8] },

    // Label commands
    Clabel { args: &'a [u8] },
    ClabelCommit,

    // Multi-line commands: opens a payload block; its body is returned later
    // by parse_payload_block.
    Json { args: &'a [u8] },

    // The body of a payload block, returned as one chunk when the end-marker
    // line is found.
    FunctionResultPayload { data: &'a [u8] },
    FunctionPayloadData { data: &'a [u8] },

    // Shutdown
    Quit,

    /// First word is not in the keyword map (`Token`); `MessageParser` logs
    /// and drops it.
    Unknown,

    /// Declared but never produced: an empty line yields `command: None` on
    /// [`ParsedLine`].
    EmptyLine,
}

// Debug impl: byte payloads render through `ByteStr` (escaped, printable)
// instead of raw bytes.
impl core::fmt::Debug for Command<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Command::Chart { args } => f
                .debug_struct("Chart")
                .field("args", &ByteStr(args))
                .finish(),
            Command::Dimension { args } => f
                .debug_struct("Dimension")
                .field("args", &ByteStr(args))
                .finish(),
            Command::Variable { args } => f
                .debug_struct("Variable")
                .field("args", &ByteStr(args))
                .finish(),
            Command::ChartDefinitionEnd => f.write_str("ChartDefinitionEnd"),
            Command::Begin { args } => f
                .debug_struct("Begin")
                .field("args", &ByteStr(args))
                .finish(),
            Command::Set { args } => f.debug_struct("Set").field("args", &ByteStr(args)).finish(),
            Command::End { args } => f.debug_struct("End").field("args", &ByteStr(args)).finish(),
            Command::Function { args } => f
                .debug_struct("Function")
                .field("args", &ByteStr(args))
                .finish(),
            Command::FunctionPayloadBegin { args } => f
                .debug_struct("FunctionPayloadBegin")
                .field("args", &ByteStr(args))
                .finish(),
            Command::FunctionPayload { args } => f
                .debug_struct("FunctionPayload")
                .field("args", &ByteStr(args))
                .finish(),
            Command::Clabel { args } => f
                .debug_struct("Clabel")
                .field("args", &ByteStr(args))
                .finish(),
            Command::ClabelCommit => f.write_str("ClabelCommit"),
            Command::Json { args } => f
                .debug_struct("Json")
                .field("args", &ByteStr(args))
                .finish(),
            Command::FunctionResultPayload { data } => f
                .debug_struct("FunctionResultPayload")
                .field("data", &ByteStr(data))
                .finish(),
            Command::FunctionPayloadData { data } => f
                .debug_struct("FunctionPayloadData")
                .field("data", &ByteStr(data))
                .finish(),
            Command::Quit => f.write_str("Quit"),
            Command::Unknown => f.debug_struct("Unknown").finish(),
            Command::EmptyLine => f.write_str("EmptyLine"),
            Command::FunctionResultBegin { args } => f
                .debug_struct("FunctionResultBegin")
                .field("data", &ByteStr(args))
                .finish(),
            Command::FunctionResultEnd { args } => f
                .debug_struct("FunctionResultEnd")
                .field("data", &ByteStr(args))
                .finish(),
            Command::FunctionCancel { args } => f
                .debug_struct("FunctionCancel")
                .field("args", &ByteStr(args))
                .finish(),
            Command::FunctionProgress { args } => f
                .debug_struct("FunctionProgress")
                .field("args", &ByteStr(args))
                .finish(),
        }
    }
}

// Debug helper: renders a byte slice as a quoted string, escaping newline,
// tab, backslash, quote and non-printable bytes as \xNN.
struct ByteStr<'a>(&'a [u8]);

impl core::fmt::Debug for ByteStr<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "\"")?;
        for &byte in self.0 {
            match byte {
                b'\n' => write!(f, "\\n")?,
                b'\r' => write!(f, "\\r")?,
                b'\t' => write!(f, "\\t")?,
                b'\\' => write!(f, "\\\\")?,
                b'"' => write!(f, "\\\"")?,
                0x20..=0x7E => write!(f, "{}", byte as char)?,
                _ => write!(f, "\\x{:02x}", byte)?,
            }
        }
        write!(f, "\"")?;
        Ok(())
    }
}

/// One parse result, borrowing from the buffer passed to [`LineParser::parse`].
#[derive(Debug)]
pub struct ParsedLine<'a> {
    /// `None` for an empty or all-whitespace line, which the caller skips.
    pub command: Option<Command<'a>>,
    /// Bytes consumed from the front of the buffer passed to `parse`: through
    /// the line's `\n`, or through the end-marker line's `\n` for a payload
    /// block.
    pub consumed: usize,
}

/// Parser state for multi-line payload blocks. A block opens when the begin
/// keyword is parsed and closes when `parse` finds the matching end-marker
/// line; while open, the body bypasses keyword lookup entirely and is
/// returned as one payload command.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ParserState {
    /// Normal line-by-line parsing mode
    Normal,
    /// Inside a FUNCTION_RESULT block, looking for FUNCTION_RESULT_END
    FunctionResult,
    /// Inside a FUNCTION_PAYLOAD block, looking for FUNCTION_PAYLOAD_END
    FunctionPayload,
    /// Inside a JSON block, looking for JSON_PAYLOAD_END
    JsonPayload,
}

impl Default for ParserState {
    fn default() -> Self {
        Self::Normal
    }
}

/// Low-level line parser. Stateful across calls: it must always be fed
/// successive slices of the same stream (as `tokio_codec::Decoder` does); a
/// fresh parser cannot resume a payload block opened by another one.
#[derive(Default, Debug)]
pub struct LineParser {
    state: ParserState,
    /// Offset into the buffer where payload data starts; always 0 because
    /// callers drop consumed bytes between `parse` calls, so this mainly
    /// marks that a block is open (`Some`) or not (`None`).
    payload_start: Option<usize>,
}

impl LineParser {
    /// Parse the next line or payload block from `buffer`. Returns
    /// `Err(IncompleteLine)` when `buffer` does not yet hold a complete line
    /// or block; the caller then keeps the buffer and feeds more bytes (as
    /// `tokio_codec::Decoder` does). Inside a payload block, `buffer` must
    /// start at the first payload byte — the begin line must already be
    /// consumed.
    pub fn parse<'a>(&mut self, buffer: &'a [u8]) -> Result<ParsedLine<'a>> {
        match self.state {
            ParserState::Normal => self.parse_normal_line(buffer),
            ParserState::FunctionResult => self.parse_payload_block(buffer, b"FUNCTION_RESULT_END"),
            ParserState::FunctionPayload => {
                self.parse_payload_block(buffer, b"FUNCTION_PAYLOAD_END")
            }
            ParserState::JsonPayload => self.parse_payload_block(buffer, b"JSON_PAYLOAD_END"),
        }
    }

    /// Parse one normal line: everything up to the next `\n` is split by
    /// `WordIterator`; the first word is the keyword, the rest becomes `args`.
    fn parse_normal_line<'a>(&mut self, buffer: &'a [u8]) -> Result<ParsedLine<'a>> {
        let Some(newline_pos) = find_byte(buffer, b'\n') else {
            return Err(Error::IncompleteLine);
        };

        let mut words = WordIterator::new(&buffer[..newline_pos]);
        let consumed = newline_pos + 1;

        let Some(token) = words.next() else {
            return Ok(ParsedLine {
                command: None,
                consumed,
            });
        };

        // Everything after the keyword, passed through un-split (quoting
        // rules live in WordIterator/message_parser).
        let args = words.remainder();

        // Keyword lookup in the phf map generated by build.rs.
        let command = match COMMAND_MAP.get(token) {
            Some(Token::Chart) => Command::Chart { args },
            Some(Token::ChartDefinitionEnd) => Command::ChartDefinitionEnd,
            Some(Token::Dimension) => Command::Dimension { args },
            Some(Token::Clabel) => Command::Clabel { args },
            Some(Token::ClabelCommit) => Command::ClabelCommit,

            Some(Token::Begin) => Command::Begin { args },
            Some(Token::Set) => Command::Set { args },
            Some(Token::End) => Command::End { args },
            Some(Token::Function) => Command::Function { args },
            // Block openers: switch state; the body is returned as one chunk
            // by a later parse() call (see parse_payload_block).
            Some(Token::FunctionResultBegin) => {
                self.state = ParserState::FunctionResult;
                self.payload_start = Some(0);
                Command::FunctionResultBegin { args }
            }
            Some(Token::FunctionResultEnd) => Command::FunctionResultEnd { args },
            Some(Token::FunctionPayloadBegin) => {
                self.state = ParserState::FunctionPayload;
                self.payload_start = Some(0);
                Command::FunctionPayloadBegin { args }
            }
            Some(Token::FunctionPayloadEnd) => Command::FunctionPayload { args },
            Some(Token::FunctionProgress) => Command::FunctionProgress { args },
            Some(Token::FunctionCancel) => Command::FunctionCancel { args },
            Some(Token::Json) => {
                self.state = ParserState::JsonPayload;
                self.payload_start = Some(0);
                Command::Json { args }
            }

            Some(Token::Quit) => Command::Quit,
            // A map entry without a match arm: a keyword was added to
            // build.rs but not handled here.
            Some(token) => {
                panic!("Unhandled line parser token: {:#?}", token)
            }
            // Keyword outside this parser's vocabulary.
            None => Command::Unknown,
        };

        Ok(ParsedLine {
            command: Some(command),
            consumed,
        })
    }

    /// Consume a payload block: scan lines for one exactly equal to
    /// `end_marker` and return everything before it as a single payload
    /// command. The payload excludes the `\n` before the marker; an empty
    /// block yields empty data. Returns `IncompleteLine` until the marker
    /// line is complete; no size limit is enforced, so the caller keeps the
    /// whole block buffered until the marker arrives.
    fn parse_payload_block<'a>(
        &mut self,
        buffer: &'a [u8],
        end_marker: &[u8],
    ) -> Result<ParsedLine<'a>> {
        let start_offset = self.payload_start.unwrap_or(0);

        // No payload bytes to scan yet (empty buffer view).
        if start_offset >= buffer.len() {
            return Err(Error::IncompleteLine);
        }

        // Scan line by line for the end marker; non-matching payload lines
        // are skipped here and ride along in the final payload chunk.
        let search_buffer = &buffer[start_offset..];
        let mut pos = 0;

        while pos < search_buffer.len() {
            if let Some(newline_pos) = find_byte(&search_buffer[pos..], b'\n') {
                let line_start = pos;
                let line_end = pos + newline_pos;
                let line = &search_buffer[line_start..line_end];

                // Check if this line is the end marker
                if line == end_marker {
                    // Found the end marker
                    let payload_end = line_start; // End of payload (before the end marker line)
                    let consumed = start_offset + line_end + 1; // Total consumed from original buffer

                    // The payload is everything from start to just before the end marker
                    let payload = if payload_end > 0 {
                        &search_buffer[..payload_end - 1] // Exclude the newline before end marker
                    } else {
                        b"" // Empty payload
                    };

                    let command = match self.state {
                        ParserState::FunctionResult => {
                            Command::FunctionResultPayload { data: payload }
                        }
                        ParserState::FunctionPayload => {
                            Command::FunctionPayloadData { data: payload }
                        }
                        // JSON blocks reuse the function-result command;
                        // MessageParser keeps no open JSON message, so this
                        // payload is dropped there.
                        ParserState::JsonPayload => {
                            Command::FunctionResultPayload { data: payload }
                        } // JSON uses same as function result
                        ParserState::Normal => {
                            unreachable!("Should not be parsing payload in Normal state")
                        }
                    };

                    self.state = ParserState::Normal;
                    self.payload_start = None;

                    return Ok(ParsedLine {
                        command: Some(command),
                        consumed,
                    });
                }

                // Move to the next line
                pos = line_end + 1;
            } else {
                // No complete line found, need more data
                return Err(Error::IncompleteLine);
            }
        }

        Err(Error::IncompleteLine)
    }
}

/// Index of the first occurrence of `needle` in `haystack` (linear scan).
fn find_byte(haystack: &[u8], needle: u8) -> Option<usize> {
    haystack.iter().position(|&b| b == needle)
}
