// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("journaldexporter")
	ScopeName = "github.com/netdata/netdata/otel-collector/exporter/journaldexporter"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
