#!/bin/sh

set -e

case "$1" in
  configure|reconfigure)
    chown root:netdata /usr/libexec/netdata/plugins.d/otel-plugin
    chmod 0750 /usr/libexec/netdata/plugins.d/otel-plugin
    ;;
esac

exit 0
