#!/bin/sh

set -e

case "$1" in
  configure|reconfigure)
    chown root:netdata /usr/libexec/netdata/plugins.d/nom.plugin
    chmod 0750 /usr/libexec/netdata/plugins.d/nom.plugin
    if ! setcap "cap_net_bind_service=eip" /usr/libexec/netdata/plugins.d/nom.plugin; then
        chmod -f 4750 /usr/libexec/netdata/plugins.d/nom.plugin
    fi
    ;;
esac

exit 0