/**
 * Phase 2 deterministic test harness infrastructure.
 * Re-exports all infrastructure modules for convenience.
 */

// Type definitions
export type {
  ExecuteTurnHandler,
  HarnessTest,
  PassThroughHandler,
  PhaseOneRunOptions,
  ScenarioRunOutput,
  TestContext,
  TestRunResult,
} from './harness-types.js';

// Helper functions
export {
  assertRecord,
  createDeferred,
  decodeBase64,
  delay,
  expectLogDetailNumber,
  expectLogEvent,
  expectRecord,
  expectTurnFailureContains,
  expectTurnFailureSlugs,
  extractNonceFromMessages,
  findLogByEvent,
  findLogByIdentifier,
  findTurnFailedMessage,
  formatDurationMs,
  getLogDetail,
  getLogsByIdentifier,
  getPrivateField,
  getPrivateMethod,
  invariant,
  isRecord,
  LOG_EVENTS,
  LOG_TURN_FAILURE,
  logHasDetail,
  logHasEvent,
  parseDumpList,
  parseScenarioFilter,
  RUN_LOG_DECIMAL_PRECISION,
  runWithTimeout,
  safeJsonByteLengthLocal,
  estimateMessagesBytesLocal,
  stripAnsiCodes,
  toError,
  toErrorMessage,
} from './harness-helpers.js';

// Mock classes and factories
export {
  BASE_DEFAULTS,
  buildInMemoryConfigLayers,
  createParentSessionStub,
  defaultPersistenceCallbacks,
  HarnessSharedHandle,
  HarnessSharedRegistry,
  isLlmAccounting,
  isToolAccounting,
  makeBasicConfiguration,
  makeSuccessResult,
  makeTempDir,
  MODEL_NAME,
  PRIMARY_PROVIDER,
  SECONDARY_PROVIDER,
  TMP_PREFIX,
} from './harness-mocks.js';

// Runner functions
export {
  cleanupActiveHandles,
  DEFAULT_SCENARIO_TIMEOUT_MS,
  formatFailureHint,
  getEffectiveTimeoutMs,
  PHASE2_FORCE_SEQUENTIAL,
  PHASE2_MODE,
  PHASE2_PARALLEL_CONCURRENCY,
  resetStateBetweenBatches,
  resetStateBetweenSequentialTests,
  runParallelBatch,
  runWithExecuteTurnOverride,
  runWithPassThroughCapture,
} from './harness-runner.js';

// Shared constants
export {
  BACKING_OFF_FRAGMENT,
  COLLAPSE_FIXED_RESULT,
  COLLAPSE_RECOVERY_RESULT,
  CONTEXT_FORCING_FRAGMENT,
  CONTEXT_LIMIT_TURN_WARN,
  CONTEXT_OVERFLOW_FRAGMENT,
  CONTEXT_REMOTE,
  COVERAGE_CHILD_BODY,
  COVERAGE_CHILD_TOOL,
  COVERAGE_PARENT_BODY,
  DEFAULT_PROMPT_SCENARIO,
  FINAL_REPORT_MAX_RETRIES_SCENARIO,
  FINAL_REPORT_RETRY_TEXT_SCENARIO,
  FINAL_REPORT_TOOL_MESSAGE_SCENARIO,
  FINAL_TURN_FRAGMENT,
  FINAL_TURN_REMOTE,
  FIXTURE_PREEMPT_REASON,
  HISTORY_ASSISTANT_SEED,
  HISTORY_SYSTEM_SEED,
  MAX_RETRY_SUCCESS_RESULT,
  MINIMAL_SYSTEM_PROMPT,
  PRIMARY_REMOTE,
  PURE_TEXT_RETRY_RESULT,
  RESTART_POST_PAYLOAD,
  RESTART_TRIGGER_PAYLOAD,
  RETRY_EXHAUSTED_MESSAGE,
  RETRY_REMOTE,
  ROUTER_CHILD_REPORT_CONTENT,
  ROUTER_HANDOFF_TOOL,
  ROUTER_PARENT_REPORT_CONTENT,
  ROUTER_ROUTE_MESSAGE,
  RUN_TEST_11,
  RUN_TEST_21,
  RUN_TEST_31,
  RUN_TEST_33,
  RUN_TEST_37,
  RUN_TEST_MAX_TURN_LIMIT,
  SECOND_TURN_FINAL_ANSWER,
  SHARED_REGISTRY_RESULT,
  SNAPSHOT_FULL_MARKER,
  STATUS_UPDATE_RESPONSE,
  SUBAGENT_TOOL,
  TASK_ANALYSIS_COMPLETE,
  TASK_COMPLETE_REPORT,
  TASK_COMPLETE_TASK,
  TASK_COMPLETED_RESPONSE,
  TASK_CONTINUE_PROCESSING,
  TASK_STATUS_COMPLETED,
  TASK_STATUS_IN_PROGRESS,
  TEXT_EXTRACTION_INVALID_TEXT_RESULT,
  TEXT_EXTRACTION_RETRY_RESULT,
  THINK_TAG_INNER,
  THINK_TAG_NONSTREAM_FRAGMENT,
  THINK_TAG_STREAM_FRAGMENT,
  THRESHOLD_ABOVE_USER_PROMPT,
  THRESHOLD_SYSTEM_PROMPT,
  THRESHOLD_USER_PROMPT,
  TOKENIZER_GPT4O,
  TOOL_OUTPUT_HANDLE_PATTERN,
  TOOL_OUTPUT_HANDLE_PREFIX,
  TOOL_OUTPUT_STORE_LOG_FRAGMENT,
} from './harness-constants.js';
