# SPDX-License-Identifier: GPL-3.0-or-later
# Function to provide information regarding the Netdata version.
#
# The high-level logic is (a) use git-describe, (b) fallback to info from
# packaging/version. This version field is used for cmake's project,
# cpack's packaging, and the agent's functionality.
function(netdata_version)
  find_package(Git)

  if(GIT_EXECUTABLE)
    execute_process(COMMAND ${GIT_EXECUTABLE} describe
                    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
                    RESULT_VARIABLE GIT_DESCRIBE_RESULT
                    OUTPUT_VARIABLE GIT_DESCRIBE_OUTPUT)
    if(GIT_DESCRIBE_RESULT)
      file(STRINGS "${CMAKE_SOURCE_DIR}/packaging/version" GIT_DESCRIBE_OUTPUT)
      message(WARNING "using version from packaging/version: '${GIT_DESCRIBE_OUTPUT}'")
    endif()
  else()
    file(STRINGS packaging/version GIT_DESCRIBE_OUTPUT)
    message(WARNING "using version from packaging/version: '${GIT_DESCRIBE_OUTPUT}'")
  endif()

  string(STRIP ${GIT_DESCRIBE_OUTPUT} GIT_DESCRIBE_OUTPUT)
  set(NETDATA_VERSION_STRING "${GIT_DESCRIBE_OUTPUT}" PARENT_SCOPE)

  string(REGEX MATCH "v?([0-9]+)\\.([0-9]+)\\.([0-9]+)-rc([0-9]+)(-([0-9]+)-g([0-9a-f]+))?" MATCHES "${GIT_DESCRIBE_OUTPUT}")
  if(CMAKE_MATCH_COUNT EQUAL 4)
    set(version_major ${CMAKE_MATCH_1})
    set(version_minor ${CMAKE_MATCH_2})
    set(version_patch ${CMAKE_MATCH_3})
    set(version_tweak ${CMAKE_MATCH_4})
    set(version_descr "N/A")
    set(version_type "release-candidate")
  elseif(CMAKE_MATCH_COUNT EQUAL 7)
    set(version_major ${CMAKE_MATCH_1})
    set(version_minor ${CMAKE_MATCH_2})
    set(version_patch ${CMAKE_MATCH_3})
    set(version_tweak ${CMAKE_MATCH_4})
    set(version_descr "rc.${CMAKE_MATCH_6}.g${CMAKE_MATCH_7}")
    set(version_type "git")
  else()
    string(REGEX MATCH "v?([0-9]+)\\.([0-9]+)\\.([0-9]+)-?([0-9]+)?-?([0-9a-zA-Z]+)?" MATCHES "${GIT_DESCRIBE_OUTPUT}")
    if(CMAKE_MATCH_COUNT EQUAL 3)
      set(version_major ${CMAKE_MATCH_1})
      set(version_minor ${CMAKE_MATCH_2})
      set(version_patch ${CMAKE_MATCH_3})
      set(version_tweak 0)
      set(version_descr "N/A")
      set(version_type "stable")
    elseif(CMAKE_MATCH_COUNT EQUAL 4)
      set(version_major ${CMAKE_MATCH_1})
      set(version_minor ${CMAKE_MATCH_2})
      set(version_patch ${CMAKE_MATCH_3})
      set(version_tweak ${CMAKE_MATCH_4})
      set(version_descr "N/A")
      set(version_type "git")
    elseif(CMAKE_MATCH_COUNT EQUAL 5)
      set(version_major ${CMAKE_MATCH_1})
      set(version_minor ${CMAKE_MATCH_2})
      set(version_patch ${CMAKE_MATCH_3})
      set(version_tweak ${CMAKE_MATCH_4})
      set(version_descr ${CMAKE_MATCH_5})
      set(version_type "git")
    else()
      message(FATAL_ERROR "Wrong version regex match count ${CMAKE_MATCH_COUNT} (should be in 3, 4 or 5)")
    endif()
  endif()

  if(version_type STREQUAL "stable")
    set(NETDATA_PACKAGE_VERSION ${version_major}.${version_minor}.${version_patch} PARENT_SCOPE)
  elseif(version_type STREQUAL "release-candidate")
    set(NETDATA_PACKAGE_VERSION ${version_major}.${version_minor}.${version_patch}~rc${version_tweak} PARENT_SCOPE)
  else()
    set(NETDATA_PACKAGE_VERSION ${version_major}.${version_minor}.${version_patch}.${version_tweak}.${version_descr} PARENT_SCOPE)
  endif()

  set(NETDATA_VERSION_MAJOR "${version_major}" PARENT_SCOPE)
  set(NETDATA_VERSION_MINOR "${version_minor}" PARENT_SCOPE)
  set(NETDATA_VERSION_PATCH "${version_patch}" PARENT_SCOPE)
  set(NETDATA_VERSION_TWEAK "${version_tweak}" PARENT_SCOPE)
  set(NETDATA_VERSION_DESCR "${version_descr}" PARENT_SCOPE)
  set(NETDATA_VERSION_TYPE "${version_type}" PARENT_SCOPE)
endfunction()
