// SPDX-License-Identifier: GPL-3.0-or-later

package registry

var kindSpecs = []KindSpec{
	{ID: "service", Display: "Redfish Service", TopFamily: "Overview", LeafFamily: "service", ComponentFamily: "service", ComponentClass: "service", ParentPresentationRank: 0},
	{ID: "system", Display: "System", TopFamily: "Overview", LeafFamily: "system", ComponentFamily: "system", ComponentClass: "system", ParentPresentationRank: 1},
	{ID: "chassis", Display: "Chassis", TopFamily: "Overview", LeafFamily: "chassis", ComponentFamily: "chassis", ComponentClass: "resource", ParentPresentationRank: 2},
	{ID: "manager", Display: "Manager", TopFamily: "Management", LeafFamily: "manager", ComponentFamily: "manager", ComponentClass: "resource", ParentPresentationRank: 3},
	{ID: "processor", Display: "Processor", TopFamily: "Compute", LeafFamily: "processor", ComponentFamily: "processor", ComponentClass: "replaceable", ParentPresentationRank: 4},
	{ID: "processor_core", Display: "Processor Core", TopFamily: "Compute", LeafFamily: "processor_core", ComponentFamily: "processor_core", ComponentClass: "resource", ParentPresentationRank: 5},
	{ID: "memory", Display: "Memory Module", TopFamily: "Memory", LeafFamily: "memory", ComponentFamily: "memory", ComponentClass: "replaceable", ParentPresentationRank: 6},
	{ID: "storage", Display: "Storage", TopFamily: "Storage", LeafFamily: "storage", ComponentFamily: "storage", ComponentClass: "resource", ParentPresentationRank: 7},
	{ID: "storage_controller", Display: "Storage Controller", TopFamily: "Storage", LeafFamily: "storage_controller", ComponentFamily: "storage_controller", ComponentClass: "replaceable", ParentPresentationRank: 8},
	{ID: "drive", Display: "Drive", TopFamily: "Storage", LeafFamily: "drive", ComponentFamily: "drive", ComponentClass: "replaceable", ParentPresentationRank: 9},
	{ID: "volume", Display: "Volume", TopFamily: "Storage", LeafFamily: "volume", ComponentFamily: "volume", ComponentClass: "resource", ParentPresentationRank: 10},
	{ID: "network_adapter", Display: "Network Adapter", TopFamily: "Network", LeafFamily: "network_adapter", ComponentFamily: "network_adapter", ComponentClass: "network", ParentPresentationRank: 11},
	{ID: "network_device_function", Display: "Network Device Function", TopFamily: "Network", LeafFamily: "network_device_function", ComponentFamily: "network_device_function", ComponentClass: "network", ParentPresentationRank: 12},
	{ID: "ethernet_interface", Display: "Ethernet Interface", TopFamily: "Network", LeafFamily: "ethernet_interface", ComponentFamily: "ethernet_interface", ComponentClass: "network", ParentPresentationRank: 13},
	{ID: "network_interface", Display: "Network Interface", TopFamily: "Network", LeafFamily: "network_interface", ComponentFamily: "network_interface", ComponentClass: "network", ParentPresentationRank: 14},
	{ID: "network_port", Display: "Network Port", TopFamily: "Network", LeafFamily: "network_port", ComponentFamily: "network_port", ComponentClass: "network", ParentPresentationRank: 15},
	{ID: "port", Display: "Port", TopFamily: "Network", LeafFamily: "port", ComponentFamily: "port", ComponentClass: "network", ParentPresentationRank: 16},
	{ID: "pcie_device", Display: "PCIe Device", TopFamily: "Network", LeafFamily: "pcie_device", ComponentFamily: "pcie_device", ComponentClass: "replaceable", ParentPresentationRank: 17},
	{ID: "pcie_function", Display: "PCIe Function", TopFamily: "Network", LeafFamily: "pcie_function", ComponentFamily: "pcie_function", ComponentClass: "network", ParentPresentationRank: 18},
	{ID: "fan", Display: "Fan", TopFamily: "Thermal", LeafFamily: "fan", ComponentFamily: "fan", ComponentClass: "replaceable", ParentPresentationRank: 19},
	{ID: "pump", Display: "Pump", TopFamily: "Thermal", LeafFamily: "pump", ComponentFamily: "pump", ComponentClass: "replaceable", ParentPresentationRank: 20},
	{ID: "power_supply", Display: "Power Supply", TopFamily: "Power", LeafFamily: "power_supply", ComponentFamily: "power_supply", ComponentClass: "replaceable", ParentPresentationRank: 21},
	{ID: "battery", Display: "Battery", TopFamily: "Power", LeafFamily: "battery", ComponentFamily: "battery", ComponentClass: "replaceable", ParentPresentationRank: 22},
	{ID: "sensor", Display: "Sensor", TopFamily: "Overview", LeafFamily: "sensor", ComponentFamily: "sensor", ComponentClass: "reading", ParentPresentationRank: 23},
	{ID: "redundancy", Display: "Redundancy", TopFamily: "Overview", LeafFamily: "redundancy", ComponentFamily: "redundancy", ComponentClass: "resource", ParentPresentationRank: 24},
	{ID: "thermal_subsystem", Display: "Thermal Subsystem", TopFamily: "Thermal", LeafFamily: "thermal_subsystem", ComponentFamily: "thermal_subsystem", ComponentClass: "resource", ParentPresentationRank: 25},
	{ID: "power_subsystem", Display: "Power Subsystem", TopFamily: "Power", LeafFamily: "power_subsystem", ComponentFamily: "power_subsystem", ComponentClass: "resource", ParentPresentationRank: 26},
	{ID: "coolant_connector", Display: "Coolant Connector", TopFamily: "Thermal", LeafFamily: "coolant_connector", ComponentFamily: "coolant_connector", ComponentClass: "replaceable", ParentPresentationRank: 27},
	{ID: "filter", Display: "Filter", TopFamily: "Thermal", LeafFamily: "filter", ComponentFamily: "filter", ComponentClass: "replaceable", ParentPresentationRank: 28},
	{ID: "heater", Display: "Heater", TopFamily: "Thermal", LeafFamily: "heater", ComponentFamily: "heater", ComponentClass: "replaceable", ParentPresentationRank: 29},
	{ID: "leak_detection", Display: "Leak Detection", TopFamily: "Thermal", LeafFamily: "leak_detection", ComponentFamily: "leak_detection", ComponentClass: "resource", ParentPresentationRank: 30},
	{ID: "leak_detector_group", Display: "Leak Detector Group", TopFamily: "Thermal", LeafFamily: "leak_detector_group", ComponentFamily: "leak_detector_group", ComponentClass: "resource", ParentPresentationRank: 31},
	{ID: "leak_detector", Display: "Leak Detector", TopFamily: "Thermal", LeafFamily: "leak_detector", ComponentFamily: "leak_detector", ComponentClass: "replaceable", ParentPresentationRank: 32},
	{ID: "control", Display: "Control", TopFamily: "Thermal", LeafFamily: "control", ComponentFamily: "control", ComponentClass: "resource", ParentPresentationRank: 33},
	{ID: "firmware", Display: "Firmware", TopFamily: "Management", LeafFamily: "firmware", ComponentFamily: "firmware", ComponentClass: "resource", ParentPresentationRank: 34},
	{ID: "software", Display: "Software", TopFamily: "Management", LeafFamily: "software", ComponentFamily: "software", ComponentClass: "resource", ParentPresentationRank: 35},
	{ID: "assembly", Display: "Assembly", TopFamily: "Management", LeafFamily: "assembly", ComponentFamily: "assembly", ComponentClass: "resource", ParentPresentationRank: 36},
	{ID: "log_service", Display: "Log Service", TopFamily: "Management", LeafFamily: "log_service", ComponentFamily: "log_service", ComponentClass: "log_service", ParentPresentationRank: 37},
}

var statusSpecs = []StatusSpec{
	{Kind: "service"},
	{Kind: "system", Status: true, PowerState: true},
	{Kind: "chassis", Status: true, PowerState: true},
	{Kind: "manager", Status: true, PowerState: true},
	{Kind: "processor", Status: true, PowerState: true, AggregateKinds: []Kind{"system", "chassis"}},
	{Kind: "processor_core", AggregateKinds: []Kind{"processor"}},
	{Kind: "memory", Status: true, AggregateKinds: []Kind{"system", "chassis"}},
	{Kind: "storage", Status: true, AggregateKinds: []Kind{"system"}},
	{Kind: "storage_controller", Status: true, AggregateKinds: []Kind{"storage"}},
	{Kind: "drive", Status: true, FailurePredicted: true, AggregateKinds: []Kind{"storage", "chassis"}},
	{Kind: "volume", Status: true, AggregateKinds: []Kind{"storage"}},
	{Kind: "network_adapter", Status: true, AggregateKinds: []Kind{"chassis"}},
	{Kind: "network_device_function", Status: true, AggregateKinds: []Kind{"network_adapter", "network_interface"}},
	{Kind: "ethernet_interface", Status: true, AggregateKinds: []Kind{"system", "manager"}},
	{Kind: "network_interface", Status: true, AggregateKinds: []Kind{"network_adapter"}},
	{Kind: "network_port", Status: true, AggregateKinds: []Kind{"network_adapter", "network_interface"}},
	{Kind: "port", Status: true, AggregateKinds: []Kind{"processor", "storage_controller", "network_adapter", "network_interface"}},
	{Kind: "pcie_device", Status: true, AggregateKinds: []Kind{"system", "chassis"}},
	{Kind: "pcie_function", Status: true, AggregateKinds: []Kind{"pcie_device", "system"}},
	{Kind: "fan", Status: true, AggregateKinds: []Kind{"thermal_subsystem", "chassis"}},
	{Kind: "pump", Status: true, AggregateKinds: []Kind{"thermal_subsystem", "chassis"}},
	{Kind: "power_supply", Status: true, AggregateKinds: []Kind{"power_subsystem", "chassis"}},
	{Kind: "battery", Status: true, AggregateKinds: []Kind{"power_subsystem", "chassis"}},
	{Kind: "sensor", Status: true},
	{Kind: "redundancy", Status: true},
	{Kind: "thermal_subsystem", Status: true, AggregateKinds: []Kind{"chassis"}},
	{Kind: "power_subsystem", Status: true, AggregateKinds: []Kind{"chassis"}},
	{Kind: "coolant_connector", Status: true, AggregateKinds: []Kind{"thermal_subsystem", "chassis"}},
	{Kind: "filter", Status: true, AggregateKinds: []Kind{"thermal_subsystem", "chassis"}},
	{Kind: "heater", Status: true, AggregateKinds: []Kind{"thermal_subsystem", "chassis"}},
	{Kind: "leak_detection", Status: true, AggregateKinds: []Kind{"thermal_subsystem", "chassis"}},
	{Kind: "leak_detector_group", Status: true, AggregateKinds: []Kind{"leak_detection"}},
	{Kind: "leak_detector", Status: true, AggregateKinds: []Kind{"leak_detector_group", "leak_detection", "chassis"}},
	{Kind: "control", Status: true, AggregateKinds: []Kind{"chassis"}},
	{Kind: "firmware", Status: true},
	{Kind: "software", Status: true},
	{Kind: "assembly", Status: true},
	{Kind: "log_service", Status: true, AggregateKinds: []Kind{"system", "chassis", "manager"}},
}
