// SPDX-License-Identifier: GPL-3.0-or-later

package registry

var operationalSpecs = []OperationalSpec{
	{
		Order: 0, TopFamily: "Collection", LeafFamily: "collection",
		InstanceLabels: []string{"endpoint_key"},
		Metric:         "collection_status", Context: "redfish.collection.status",
		Title: "Redfish Collection Status", Units: "state",
		Incremental: false, Float: false,
		Dimensions: []string{"success", "partial", "unavailable"},
	},
	{
		Order: 1, TopFamily: "Collection", LeafFamily: "collection",
		InstanceLabels: []string{"endpoint_key"},
		Metric:         "collection_failures", Context: "redfish.collection.failures",
		Title: "Redfish Collection Failures", Units: "failures",
		Incremental: false, Float: false,
		Dimensions: []string{"auth", "tls", "transport", "timeout", "protocol", "limit", "internal"},
	},
	{
		Order: 2, TopFamily: "Collection", LeafFamily: "collection",
		InstanceLabels: []string{"endpoint_key"},
		Metric:         "collection_duration_seconds", Context: "redfish.collection.duration",
		Title: "Redfish Collection Duration", Units: "seconds",
		Incremental: false, Float: true,
		Dimensions: []string{"duration"},
	},
	{
		Order: 3, TopFamily: "Collection", LeafFamily: "collection",
		InstanceLabels: []string{"endpoint_key"},
		Metric:         "collection_http_requests", Context: "redfish.collection.http_requests",
		Title: "Redfish Collection HTTP Requests", Units: "requests/cycle",
		Incremental: false, Float: false,
		Dimensions: []string{"started", "retried", "redirected"},
	},
	{
		Order: 4, TopFamily: "Collection", LeafFamily: "collection",
		InstanceLabels: []string{"endpoint_key"},
		Metric:         "collection_operations", Context: "redfish.collection.operations",
		Title: "Redfish Collection Operations", Units: "operations/cycle",
		Incremental: false, Float: false,
		Dimensions: []string{"successful", "failed"},
	},
	{
		Order: 5, TopFamily: "Collection", LeafFamily: "collection",
		InstanceLabels: []string{"endpoint_key"},
		Metric:         "collection_traffic_received_bytes", Context: "redfish.collection.traffic",
		Title: "Redfish Collection Traffic", Units: "bytes/cycle",
		Incremental: false, Float: false,
		Dimensions: []string{"received"},
	},
	{
		Order: 6, TopFamily: "Collection", LeafFamily: "collection",
		InstanceLabels: []string{"endpoint_key"},
		Metric:         "collection_resources", Context: "redfish.collection.resources",
		Title: "Redfish Collection Resources", Units: "resources",
		Incremental: false, Float: false,
		Dimensions: []string{"discovered", "readable", "unreadable", "unknown"},
	},
	{
		Order: 7, TopFamily: "Collection", LeafFamily: "collection",
		InstanceLabels: []string{"endpoint_key"},
		Metric:         "collection_logs_route", Context: "redfish.collection.logs_route",
		Title: "Redfish Logs Route", Units: "state",
		Incremental: false, Float: false,
		Dimensions: []string{"disabled", "ready", "unavailable"},
	},
	{
		Order: 8, TopFamily: "Collection", LeafFamily: "collection",
		InstanceLabels: []string{"endpoint_key"},
		Metric:         "collection_logs_admission", Context: "redfish.collection.logs_admission",
		Title: "Redfish Logs Admission", Units: "state",
		Incremental: false, Float: false,
		Dimensions: []string{"disabled", "ready", "over_limit", "duplicate_owner", "unknown"},
	},
	{
		Order: 9, TopFamily: "Collection", LeafFamily: "collection",
		InstanceLabels: []string{"endpoint_key"},
		Metric:         "collection_log_services", Context: "redfish.collection.log_services",
		Title: "Redfish Log Services", Units: "services",
		Incremental: false, Float: false,
		Dimensions: []string{"discovered", "selected", "admitted", "limit"},
	},
	{
		Order: 10, TopFamily: "Collection", LeafFamily: "collection",
		InstanceLabels: []string{"endpoint_key"},
		Metric:         "collection_selected_system", Context: "redfish.collection.selected_system",
		Title: "Redfish Selected System State", Units: "state",
		Incremental: false, Float: false,
		Dimensions: []string{"present", "unreadable", "absent", "unknown"},
	},
	{
		Order: 11, TopFamily: "Collection", LeafFamily: "collection",
		InstanceLabels: []string{"endpoint_key", "logical_owner_key", "component_family"},
		Metric:         "collection_detail_components", Context: "redfish.collection.detail_components",
		Title: "Redfish Component Detail Population", Units: "components",
		Incremental: false, Float: false,
		Dimensions: []string{"components", "cap"},
	},
	{
		Order: 12, TopFamily: "Collection", LeafFamily: "collection",
		InstanceLabels: []string{"endpoint_key", "logical_owner_key", "component_family"},
		Metric:         "collection_detail_gate", Context: "redfish.collection.detail_gate",
		Title: "Redfish Component Detail Gate", Units: "state",
		Incremental: false, Float: false,
		Dimensions: []string{"open", "closed"},
	},
	{
		Order: 13, TopFamily: "Collection", LeafFamily: "collection",
		InstanceLabels: []string{"endpoint_key", "logical_owner_key", "component_family"},
		Metric:         "collection_detail_evidence", Context: "redfish.collection.detail_evidence",
		Title: "Redfish Component Detail Evidence", Units: "state",
		Incremental: false, Float: false,
		Dimensions: []string{"complete", "incomplete"},
	},
	{
		Order: 14, TopFamily: "Collection", LeafFamily: "log_backend",
		InstanceLabels: []string{"backend_key"},
		Metric:         "log_backend_state", Context: "redfish.log_backend.state",
		Title: "Redfish Log Backend State", Units: "state",
		Incremental: false, Float: false,
		Dimensions: []string{"ready", "unavailable"},
	},
	{
		Order: 15, TopFamily: "Collection", LeafFamily: "log_backend",
		InstanceLabels: []string{"backend_key"},
		Metric:         "log_backend_storage_%s_bytes", Context: "redfish.log_backend.storage",
		Title: "Redfish Log Backend Storage", Units: "bytes",
		Incremental: false, Float: false,
		Dimensions: []string{"used", "target"},
	},
	{
		Order: 16, TopFamily: "Collection", LeafFamily: "log_backend",
		InstanceLabels: []string{"backend_key"},
		Metric:         "log_backend_files", Context: "redfish.log_backend.files",
		Title: "Redfish Log Backend Files", Units: "files",
		Incremental: false, Float: false,
		Dimensions: []string{"active", "archived"},
	},
	{
		Order: 17, TopFamily: "Collection", LeafFamily: "log_backend",
		InstanceLabels: []string{"backend_key"},
		Metric:         "log_backend_producers_active", Context: "redfish.log_backend.producers",
		Title: "Redfish Log Backend Producers", Units: "producers",
		Incremental: false, Float: false,
		Dimensions: []string{"active"},
	},
	{
		Order: 18, TopFamily: "Collection", LeafFamily: "log_backend",
		InstanceLabels: []string{"backend_key"},
		Metric:         "log_backend_pipeline_%s_total", Context: "redfish.log_backend.pipeline",
		Title: "Redfish Log Backend Pipeline", Units: "entries/s",
		Incremental: true, Float: false,
		Dimensions: []string{"received", "committed", "duplicate_suppressed", "write_failed"},
	},
	{
		Order: 19, TopFamily: "Collection", LeafFamily: "log_backend",
		InstanceLabels: []string{"backend_key"},
		Metric:         "log_backend_retention_files_deleted", Context: "redfish.log_backend.retention_files",
		Title: "Redfish Log Backend Retention Files", Units: "files/s",
		Incremental: true, Float: false,
		Dimensions: []string{"deleted"},
	},
	{
		Order: 20, TopFamily: "Collection", LeafFamily: "log_backend",
		InstanceLabels: []string{"backend_key"},
		Metric:         "log_backend_retention_bytes_deleted", Context: "redfish.log_backend.retention_bytes",
		Title: "Redfish Log Backend Retention Bytes", Units: "bytes/s",
		Incremental: true, Float: false,
		Dimensions: []string{"deleted"},
	},
	{
		Order: 21, TopFamily: "Collection", LeafFamily: "log_backend",
		InstanceLabels: []string{"backend_key"},
		Metric:         "log_backend_sync_duration_seconds", Context: "redfish.log_backend.sync_duration",
		Title: "Redfish Log Backend Sync Duration", Units: "seconds",
		Incremental: false, Float: true,
		Dimensions: []string{"duration"},
	},
	{
		Order: 22, TopFamily: "Management", LeafFamily: "log_service",
		InstanceLabels: []string{"endpoint_key", "resource_key"},
		Metric:         "log_service_ingestion_state", Context: "redfish.log_service.ingestion_state",
		Title: "Redfish Log Service Ingestion State", Units: "state",
		Incremental: false, Float: false,
		Dimensions: []string{"current", "backfilling", "paused_backend", "blocked_source", "unknown"},
	},
	{
		Order: 23, TopFamily: "Management", LeafFamily: "log_service",
		InstanceLabels: []string{"endpoint_key", "resource_key"},
		Metric:         "log_service_pipeline", Context: "redfish.log_service.pipeline",
		Title: "Redfish Log Service Pipeline", Units: "entries/s",
		Incremental: true, Float: false,
		Dimensions: []string{"fetched", "committed", "duplicate_suppressed", "failed"},
	},
	{
		Order: 24, TopFamily: "Management", LeafFamily: "log_service",
		InstanceLabels: []string{"endpoint_key", "resource_key"},
		Metric:         "log_service_poll_duration_seconds", Context: "redfish.log_service.poll_duration",
		Title: "Redfish Log Service Poll Duration", Units: "seconds",
		Incremental: false, Float: true,
		Dimensions: []string{"duration"},
	},
	{
		Order: 25, TopFamily: "Management", LeafFamily: "log_service",
		InstanceLabels: []string{"endpoint_key", "resource_key"},
		Metric:         "log_service_source_lag_seconds", Context: "redfish.log_service.source_lag",
		Title: "Redfish Log Service Source Lag", Units: "seconds",
		Incremental: false, Float: true,
		Dimensions: []string{"duration"},
	},
	{
		Order: 26, TopFamily: "Management", LeafFamily: "log_service",
		InstanceLabels: []string{"endpoint_key", "resource_key"},
		Metric:         "log_service_scan_mode", Context: "redfish.log_service.scan_mode",
		Title: "Redfish Log Service Scan Mode", Units: "state",
		Incremental: false, Float: false,
		Dimensions: []string{"client_context", "incremental", "full", "unordered", "unknown"},
	},
	{
		Order: 27, TopFamily: "Management", LeafFamily: "log_service",
		InstanceLabels: []string{"endpoint_key", "resource_key"},
		Metric:         "log_service_full_reconciliation_age_seconds", Context: "redfish.log_service.full_reconciliation_age",
		Title: "Redfish Log Service Full Reconciliation Age", Units: "seconds",
		Incremental: false, Float: true,
		Dimensions: []string{"duration"},
	},
	{
		Order: 28, TopFamily: "Management", LeafFamily: "log_service",
		InstanceLabels: []string{"endpoint_key", "resource_key"},
		Metric:         "log_service_reconciliation", Context: "redfish.log_service.reconciliation",
		Title: "Redfish Log Service Reconciliation Events", Units: "events/s",
		Incremental: true, Float: false,
		Dimensions: []string{"completed", "client_context_restarted", "client_context_unsupported", "outside_tail_recovered_exact", "outside_tail_ambiguous", "ordering_disqualified", "boundary_lost", "etag_unreliable"},
	},
}
