// SPDX-License-Identifier: GPL-3.0-or-later

package registry

var relationshipSpecs = []RelationshipSpec{
	{Order: 0, Parent: "service", Path: "Storage", Child: "storage", Family: "storage", Mode: RelationshipTraversal, RollupRank: -1},
	{Order: 1, Parent: "service", Path: "UpdateService", Child: "update_service", Family: "firmware", Mode: RelationshipTraversal, RollupRank: -1},
	{Order: 2, Parent: "update_service", Path: "FirmwareInventory", Child: "firmware", Family: "firmware", Mode: RelationshipTraversal, RollupRank: -1},
	{Order: 3, Parent: "update_service", Path: "SoftwareInventory", Child: "software", Family: "firmware", Mode: RelationshipTraversal, RollupRank: -1},
	{Order: 4, Parent: "system", Path: "Processors", Child: "processor", Family: "compute", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 5, Parent: "system", Path: "Memory", Child: "memory", Family: "memory", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 6, Parent: "system", Path: "Storage", Child: "storage", Family: "storage", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 7, Parent: "system", Path: "EthernetInterfaces", Child: "ethernet_interface", Family: "network", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 8, Parent: "system", Path: "NetworkInterfaces", Child: "network_interface", Family: "network", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 9, Parent: "system", Path: "PCIeDevices", Child: "pcie_device", Family: "pcie", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 10, Parent: "system", Path: "PCIeFunctions", Child: "pcie_function", Family: "pcie", Mode: RelationshipComponent, RollupRank: 1},
	{Order: 11, Parent: "system", Path: "Redundancy", Child: "redundancy", Family: "base", Mode: RelationshipComponent, Embedded: true, RollupRank: 0},
	{Order: 12, Parent: "system", Path: "LogServices", Child: "log_service", Family: "base", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 13, Parent: "system", Path: "Links.OffloadedNetworkDeviceFunctions", Child: "network_device_function", Family: "network", Mode: RelationshipAssociation, RollupRank: -1},
	{Order: 14, Parent: "chassis", Path: "Drives", Child: "drive", Family: "storage", Mode: RelationshipComponent, RollupRank: 1},
	{Order: 15, Parent: "chassis", Path: "Memory", Child: "memory", Family: "memory", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 16, Parent: "chassis", Path: "NetworkAdapters", Child: "network_adapter", Family: "network", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 17, Parent: "chassis", Path: "PCIeDevices", Child: "pcie_device", Family: "pcie", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 18, Parent: "chassis", Path: "Sensors", Child: "sensor", Family: "sensors", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 19, Parent: "chassis", Path: "Controls", Child: "control", Family: "thermal", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 20, Parent: "chassis", Path: "LeakDetectors", Child: "leak_detector", Family: "thermal", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 21, Parent: "chassis", Path: "LogServices", Child: "log_service", Family: "base", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 22, Parent: "chassis", Path: "ThermalSubsystem", Child: "thermal_subsystem", Family: "thermal", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 23, Parent: "chassis", Path: "PowerSubsystem", Child: "power_subsystem", Family: "power", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 24, Parent: "chassis", Path: "Processors", Child: "processor", Family: "compute", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 25, Parent: "chassis", Path: "Links.Storage", Child: "storage", Family: "storage", Mode: RelationshipAssociation, RollupRank: -1},
	{Order: 26, Parent: "chassis", Path: "Thermal", Child: "legacy_thermal", Family: "thermal", Mode: RelationshipLegacy, RollupRank: 0},
	{Order: 27, Parent: "chassis", Path: "Power", Child: "legacy_power", Family: "power", Mode: RelationshipLegacy, RollupRank: 0},
	{Order: 28, Parent: "chassis", Path: "EnvironmentMetrics", Child: "environment_metrics", Family: "thermal", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 29, Parent: "chassis", Path: "Assembly", Child: "assembly_document", Family: "firmware", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 30, Parent: "manager", Path: "EthernetInterfaces", Child: "ethernet_interface", Family: "network", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 31, Parent: "manager", Path: "DedicatedNetworkPorts", Child: "network_port", Family: "network", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 32, Parent: "manager", Path: "SharedNetworkPorts", Child: "network_port", Family: "network", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 33, Parent: "manager", Path: "LogServices", Child: "log_service", Family: "base", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 34, Parent: "manager", Path: "Redundancy", Child: "redundancy", Family: "base", Mode: RelationshipComponent, Embedded: true, RollupRank: 0},
	{Order: 35, Parent: "processor", Path: "Ports", Child: "port", Family: "network", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 36, Parent: "processor", Path: "Metrics", Child: "processor_metrics", Family: "compute", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 37, Parent: "processor", Path: "EnvironmentMetrics", Child: "environment_metrics", Family: "thermal", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 38, Parent: "processor", Path: "Assembly", Child: "assembly_document", Family: "firmware", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 39, Parent: "memory", Path: "Metrics", Child: "memory_metrics", Family: "memory", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 40, Parent: "memory", Path: "EnvironmentMetrics", Child: "environment_metrics", Family: "thermal", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 41, Parent: "memory", Path: "Assembly", Child: "assembly_document", Family: "firmware", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 42, Parent: "storage", Path: "Controllers", Child: "storage_controller", Family: "storage", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 43, Parent: "storage", Path: "Drives", Child: "drive", Family: "storage", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 44, Parent: "storage", Path: "Volumes", Child: "volume", Family: "storage", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 45, Parent: "storage", Path: "Redundancy", Child: "redundancy", Family: "storage", Mode: RelationshipComponent, Embedded: true, RollupRank: 0},
	{Order: 46, Parent: "storage", Path: "Metrics", Child: "storage_metrics", Family: "storage", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 47, Parent: "storage_controller", Path: "Ports", Child: "port", Family: "network", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 48, Parent: "storage_controller", Path: "Metrics", Child: "storage_controller_metrics", Family: "storage", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 49, Parent: "storage_controller", Path: "EnvironmentMetrics", Child: "environment_metrics", Family: "thermal", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 50, Parent: "storage_controller", Path: "Assembly", Child: "assembly_document", Family: "firmware", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 51, Parent: "drive", Path: "Metrics", Child: "drive_metrics", Family: "storage", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 52, Parent: "drive", Path: "EnvironmentMetrics", Child: "environment_metrics", Family: "thermal", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 53, Parent: "drive", Path: "Assembly", Child: "assembly_document", Family: "firmware", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 54, Parent: "volume", Path: "Metrics", Child: "volume_metrics", Family: "storage", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 55, Parent: "network_adapter", Path: "NetworkDeviceFunctions", Child: "network_device_function", Family: "network", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 56, Parent: "network_adapter", Path: "NetworkPorts", Child: "network_port", Family: "network", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 57, Parent: "network_adapter", Path: "Ports", Child: "port", Family: "network", Mode: RelationshipComponent, RollupRank: 1},
	{Order: 58, Parent: "network_adapter", Path: "Metrics", Child: "network_adapter_metrics", Family: "network", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 59, Parent: "network_adapter", Path: "EnvironmentMetrics", Child: "environment_metrics", Family: "thermal", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 60, Parent: "network_adapter", Path: "Assembly", Child: "assembly_document", Family: "firmware", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 61, Parent: "network_interface", Path: "NetworkDeviceFunctions", Child: "network_device_function", Family: "network", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 62, Parent: "network_interface", Path: "NetworkPorts", Child: "network_port", Family: "network", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 63, Parent: "network_interface", Path: "Ports", Child: "port", Family: "network", Mode: RelationshipComponent, RollupRank: 1},
	{Order: 64, Parent: "network_device_function", Path: "Metrics", Child: "network_device_function_metrics", Family: "network", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 65, Parent: "port", Path: "Metrics", Child: "port_metrics", Family: "network", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 66, Parent: "port", Path: "EnvironmentMetrics", Child: "environment_metrics", Family: "thermal", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 67, Parent: "pcie_device", Path: "PCIeFunctions", Child: "pcie_function", Family: "pcie", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 68, Parent: "pcie_device", Path: "EnvironmentMetrics", Child: "environment_metrics", Family: "thermal", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 69, Parent: "pcie_device", Path: "Assembly", Child: "assembly_document", Family: "firmware", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 70, Parent: "thermal_subsystem", Path: "CoolantConnectors", Child: "coolant_connector", Family: "thermal", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 71, Parent: "thermal_subsystem", Path: "Fans", Child: "fan", Family: "thermal", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 72, Parent: "thermal_subsystem", Path: "Filters", Child: "filter", Family: "thermal", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 73, Parent: "thermal_subsystem", Path: "Heaters", Child: "heater", Family: "thermal", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 74, Parent: "thermal_subsystem", Path: "Pumps", Child: "pump", Family: "thermal", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 75, Parent: "thermal_subsystem", Path: "LeakDetection", Child: "leak_detection", Family: "thermal", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 76, Parent: "thermal_subsystem", Path: "CoolantConnectorRedundancy", Child: "redundancy", Family: "thermal", Mode: RelationshipComponent, Embedded: true, RollupRank: 0},
	{Order: 77, Parent: "thermal_subsystem", Path: "FanRedundancy", Child: "redundancy", Family: "thermal", Mode: RelationshipComponent, Embedded: true, RollupRank: 0},
	{Order: 78, Parent: "thermal_subsystem", Path: "ThermalMetrics", Child: "thermal_metrics", Family: "thermal", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 79, Parent: "leak_detection", Path: "LeakDetectorGroups", Child: "leak_detector_group", Family: "thermal", Mode: RelationshipComponent, Embedded: true, RollupRank: 0},
	{Order: 80, Parent: "leak_detection", Path: "LeakDetectors", Child: "leak_detector", Family: "thermal", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 81, Parent: "leak_detector_group", Path: "Detectors", Child: "leak_detector", Family: "thermal", Mode: RelationshipComponent, Embedded: true, RollupRank: 0},
	{Order: 82, Parent: "power_subsystem", Path: "PowerSupplies", Child: "power_supply", Family: "power", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 83, Parent: "power_subsystem", Path: "Batteries", Child: "battery", Family: "power", Mode: RelationshipComponent, RollupRank: 0},
	{Order: 84, Parent: "power_subsystem", Path: "PowerSupplyRedundancy", Child: "redundancy", Family: "power", Mode: RelationshipComponent, Embedded: true, RollupRank: 0},
	{Order: 85, Parent: "power_supply", Path: "Metrics", Child: "power_supply_metrics", Family: "power", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 86, Parent: "power_supply", Path: "Assembly", Child: "assembly_document", Family: "firmware", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 87, Parent: "battery", Path: "Metrics", Child: "battery_metrics", Family: "power", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 88, Parent: "battery", Path: "Assembly", Child: "assembly_document", Family: "firmware", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 89, Parent: "sensor", Path: "SensorGroup", Child: "redundancy", Family: "sensors", Mode: RelationshipComponent, Embedded: true, RollupRank: 0},
	{Order: 90, Parent: "heater", Path: "Metrics", Child: "heater_metrics", Family: "thermal", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 91, Parent: "system", Path: "ProcessorSummary.Metrics", Child: "processor_summary_metrics", Family: "compute", Mode: RelationshipEnrichment, RollupRank: -1},
	{Order: 92, Parent: "system", Path: "MemorySummary.Metrics", Child: "memory_summary_metrics", Family: "memory", Mode: RelationshipEnrichment, RollupRank: -1},
}
