// SPDX-License-Identifier: GPL-3.0-or-later

package registry

var (
	HealthStates   = []string{"ok", "warning", "critical", "unknown"}
	ResourceStates = []string{
		"enabled", "disabled", "standby_offline", "standby_spare", "in_test", "starting",
		"absent", "unavailable_offline", "deferring", "quiesced", "updating", "qualified",
		"degraded", "unknown",
	}
	PowerStates       = []string{"on", "off", "powering_on", "powering_off", "paused", "unknown"}
	FailureStates     = []string{"clear", "predicted", "unknown"}
	AcquisitionStates = []string{"readable", "unreadable", "unknown"}
	AlarmStates       = []string{"clear", "warning", "cap", "alarm", "critical", "emergency", "fault"}
)

var stateSpecs = []StateSpec{
	{Order: 0, Kind: "chassis", Path: "PhysicalSecurity.IntrusionSensor", Metric: "chassis_intrusion_state", Context: "redfish.chassis.intrusion_state", Title: "Chassis Intrusion State", States: []string{"normal", "hardware_intrusion", "tampering_detected", "unknown"}},
	{Order: 1, Kind: "processor", Path: "Throttled", Metric: "processor_throttling_state", Context: "redfish.processor.throttling_state", Title: "Processor Throttling State", States: []string{"clear", "throttled", "unknown"}, BooleanFalse: "clear", BooleanTrue: "throttled", AggregateKinds: []Kind{"system", "chassis"}, ComponentClass: "replaceable"},
	{Order: 2, Kind: "drive", Path: "StatusIndicator", Metric: "drive_status_indicator", Context: "redfish.drive.status_indicator", Title: "Drive Status Indicator", States: []string{"ok", "fail", "rebuild", "predictive_failure_analysis", "hotspare", "in_a_critical_array", "in_a_failed_array", "unknown"}, AggregateKinds: []Kind{"storage", "chassis"}, ComponentClass: "replaceable"},
	{Order: 3, Kind: "volume", Path: "WriteCacheState", Metric: "volume_write_cache_state", Context: "redfish.volume.write_cache_state", Title: "Volume Write Cache State", States: []string{"unprotected", "protected", "degraded", "unknown"}, AggregateKinds: []Kind{"storage"}},
	{Order: 4, Kind: "ethernet_interface", Path: "LinkStatus", Metric: "ethernet_interface_link_status", Context: "redfish.ethernet_interface.link_status", Title: "Ethernet Interface Link Status", States: []string{"link_up", "no_link", "link_down", "unknown"}, AggregateKinds: []Kind{"system", "manager"}, ComponentClass: "network"},
	{Order: 5, Kind: "network_port", Path: "LinkStatus", Metric: "network_port_link_status", Context: "redfish.network_port.link_status", Title: "Network Port Link Status", States: []string{"down", "up", "starting", "training", "unknown"}, AggregateKinds: []Kind{"network_adapter", "network_interface"}, ComponentClass: "network"},
	{Order: 6, Kind: "network_port", Path: "SignalDetected", Metric: "network_port_signal_detected", Context: "redfish.network_port.signal_detected", Title: "Network Port Signal Detected", States: []string{"clear", "detected", "unknown"}, BooleanFalse: "clear", BooleanTrue: "detected", AggregateKinds: []Kind{"network_adapter", "network_interface"}, ComponentClass: "network"},
	{Order: 7, Kind: "port", Path: "LinkState", Metric: "port_link_state", Context: "redfish.port.link_state", Title: "Port Link State", States: []string{"enabled", "disabled", "unknown"}, AggregateKinds: []Kind{"processor", "storage_controller", "network_adapter", "network_interface"}, ComponentClass: "network"},
	{Order: 8, Kind: "port", Path: "LinkStatus", Metric: "port_link_status", Context: "redfish.port.link_status", Title: "Port Link Status", States: []string{"link_up", "starting", "training", "link_down", "no_link", "unknown"}, AggregateKinds: []Kind{"processor", "storage_controller", "network_adapter", "network_interface"}, ComponentClass: "network"},
	{Order: 9, Kind: "port", Path: "SignalDetected", Metric: "port_signal_detected", Context: "redfish.port.signal_detected", Title: "Port Signal Detected", States: []string{"clear", "detected", "unknown"}, BooleanFalse: "clear", BooleanTrue: "detected", AggregateKinds: []Kind{"processor", "storage_controller", "network_adapter", "network_interface"}, ComponentClass: "network"},
	{Order: 10, Kind: "power_supply", Path: "LineInputStatus", Metric: "power_supply_line_input_status", Context: "redfish.power_supply.line_input_status", Title: "Power Supply Line Input Status", States: []string{"normal", "loss_of_input", "out_of_range", "unknown"}, AggregateKinds: []Kind{"power_subsystem", "chassis"}, ComponentClass: "replaceable"},
	{Order: 11, Kind: "battery", Path: "ChargeState", Metric: "battery_charge_state", Context: "redfish.battery.charge_state", Title: "Battery Charge State", States: []string{"idle", "charging", "discharging", "unknown"}, AggregateKinds: []Kind{"power_subsystem", "chassis"}, ComponentClass: "replaceable"},
	{Order: 12, Kind: "redundancy", Path: "Mode", Metric: "redundancy_mode", Context: "redfish.redundancy.mode", Title: "Redundancy Mode", States: []string{"failover", "n_plus_m", "sharing", "sparing", "not_redundant", "unknown"}},
	{Order: 13, Kind: "redundancy", Path: "RedundancyEnabled", Metric: "redundancy_enabled", Context: "redfish.redundancy.enabled", Title: "Redundancy Enabled", States: []string{"disabled", "enabled", "unknown"}, BooleanFalse: "disabled", BooleanTrue: "enabled"},
	{Order: 14, Kind: "leak_detector", Path: "DetectorState", Metric: "leak_detector_detector_state", Context: "redfish.leak_detector.detector_state", Title: "Leak Detector State", States: []string{"ok", "warning", "critical", "unavailable", "absent", "unknown"}, AggregateKinds: []Kind{"leak_detector_group", "leak_detection", "chassis"}, ComponentClass: "replaceable"},
	{Order: 16, Kind: "system", Path: "ProcessorSummary.Status.Health", Metric: "system_processor_summary_health", Context: "redfish.system.processor_summary_health", Title: "System Processor Summary Health", States: HealthStates},
	{Order: 17, Kind: "system", Path: "ProcessorSummary.Status.HealthRollup", Metric: "system_processor_summary_health_rollup", Context: "redfish.system.processor_summary_health_rollup", Title: "System Processor Summary Health Rollup", States: HealthStates},
	{Order: 18, Kind: "system", Path: "ProcessorSummary.Status.State", Metric: "system_processor_summary_state", Context: "redfish.system.processor_summary_state", Title: "System Processor Summary State", States: ResourceStates},
	{Order: 19, Kind: "system", Path: "MemorySummary.Status.Health", Metric: "system_memory_summary_health", Context: "redfish.system.memory_summary_health", Title: "System Memory Summary Health", States: HealthStates},
	{Order: 20, Kind: "system", Path: "MemorySummary.Status.HealthRollup", Metric: "system_memory_summary_health_rollup", Context: "redfish.system.memory_summary_health_rollup", Title: "System Memory Summary Health Rollup", States: HealthStates},
	{Order: 21, Kind: "system", Path: "MemorySummary.Status.State", Metric: "system_memory_summary_state", Context: "redfish.system.memory_summary_state", Title: "System Memory Summary State", States: ResourceStates},
	{Order: 22, Kind: "storage_controller", Path: "CacheSummary.Status.Health", Metric: "storage_controller_cache_health", Context: "redfish.storage_controller.cache_health", Title: "Storage Controller Cache Health", States: HealthStates, AggregateKinds: []Kind{"storage"}, ComponentClass: "replaceable"},
	{Order: 23, Kind: "storage_controller", Path: "CacheSummary.Status.HealthRollup", Metric: "storage_controller_cache_health_rollup", Context: "redfish.storage_controller.cache_health_rollup", Title: "Storage Controller Cache Health Rollup", States: HealthStates, AggregateKinds: []Kind{"storage"}, ComponentClass: "replaceable"},
	{Order: 24, Kind: "storage_controller", Path: "CacheSummary.Status.State", Metric: "storage_controller_cache_state", Context: "redfish.storage_controller.cache_state", Title: "Storage Controller Cache State", States: ResourceStates, AggregateKinds: []Kind{"storage"}, ComponentClass: "replaceable"},
	{Order: 25, Kind: "power_supply", Document: "power_supply_metrics", Path: "Status.Health", Metric: "power_supply_metrics_health", Context: "redfish.power_supply.metrics_health", Title: "Power Supply Metrics Health", States: HealthStates, AggregateKinds: []Kind{"power_subsystem", "chassis"}, ComponentClass: "replaceable"},
	{Order: 26, Kind: "power_supply", Document: "power_supply_metrics", Path: "Status.HealthRollup", Metric: "power_supply_metrics_health_rollup", Context: "redfish.power_supply.metrics_health_rollup", Title: "Power Supply Metrics Health Rollup", States: HealthStates, AggregateKinds: []Kind{"power_subsystem", "chassis"}, ComponentClass: "replaceable"},
	{Order: 27, Kind: "power_supply", Document: "power_supply_metrics", Path: "Status.State", Metric: "power_supply_metrics_state", Context: "redfish.power_supply.metrics_state", Title: "Power Supply Metrics State", States: ResourceStates, AggregateKinds: []Kind{"power_subsystem", "chassis"}, ComponentClass: "replaceable"},
	{Order: 28, Kind: "battery", Document: "battery_metrics", Path: "Status.Health", Metric: "battery_metrics_health", Context: "redfish.battery.metrics_health", Title: "Battery Metrics Health", States: HealthStates, AggregateKinds: []Kind{"power_subsystem", "chassis"}, ComponentClass: "replaceable"},
	{Order: 29, Kind: "battery", Document: "battery_metrics", Path: "Status.HealthRollup", Metric: "battery_metrics_health_rollup", Context: "redfish.battery.metrics_health_rollup", Title: "Battery Metrics Health Rollup", States: HealthStates, AggregateKinds: []Kind{"power_subsystem", "chassis"}, ComponentClass: "replaceable"},
	{Order: 30, Kind: "battery", Document: "battery_metrics", Path: "Status.State", Metric: "battery_metrics_state", Context: "redfish.battery.metrics_state", Title: "Battery Metrics State", States: ResourceStates, AggregateKinds: []Kind{"power_subsystem", "chassis"}, ComponentClass: "replaceable"},
}
