# SPDX-License-Identifier: GPL-3.0-or-later
# Fixed instrumentation policy; keeping it in a file respects HotSpot's
# 1024-byte Attach argument limit. This is a bundled artifact, not user config.
otel.instrumentation.hikaricp.enabled=false
otel.instrumentation.common.default-enabled=false
otel.instrumentation.runtime-telemetry.enabled=true
otel.instrumentation.servlet.enabled=true
otel.instrumentation.tomcat.enabled=true
otel.instrumentation.spring-webmvc.enabled=true
otel.instrumentation.netdata-hikari.enabled=true
