# Example synthetic statsd charts configuration for two metrics: hc.foo and hc.bar

[app]
    name = hc
    metrics = hc.*
    private charts = no
    gaps when not collected = no

[hc_foo_chart]
    name = hc_foo
    title = HC Foo Metric
    family = foo
    context = hc.foo
    units = value
    priority = 91000
    type = line
    dimension = hc.foo foo last 1 1

[hc_bar_chart]
    name = hc_bar
    title = HC Bar Metric
    family = bar
    context = hc.bar
    units = value
    priority = 91001
    type = line
    dimension = hc.bar bar last 1 1
