#!/bin/sh

set -e

case "$1" in
  configure|reconfigure)
    grep /usr/libexec/netdata /var/lib/dpkg/info/netdata-plugin-logs-management.list | xargs -n 30 chown root:netdata
    chmod 0750 /usr/libexec/netdata/plugins.d/logs-management.plugin
    if ! setcap "cap_dac_read_search=eip cap_syslog=eip" /usr/libexec/netdata/plugins.d/logs-management.plugin; then
        chmod -f 4750 /usr/libexec/netdata/plugins.d/logs-management.plugin
    fi
    ;;
esac

#DEBHELPER#

exit 0
