FROM golang:1.22 AS build-env

RUN mkdir -p /workspace
WORKDIR /workspace

ENV GOOS=linux
ENV GOARCH=amd64
ENV CGO_ENABLED=0

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o go.d.plugin github.com/netdata/go.d.plugin/cmd/godplugin

FROM netdata/netdata

COPY ./mocks/netdata/netdata.conf /etc/netdata/
COPY ./mocks/conf.d /usr/lib/netdata/conf.d
COPY --from=build-env /workspace/go.d.plugin /usr/libexec/netdata/plugins.d/go.d.plugin
