// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("netdataexporter")
	ScopeName = "github.com/netdata/netdata/otel-collector/exporter/netdataexporter"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
