# Partial Ceph metric collection failure while other components continue to report data.

 template: ceph_component_collection_failed
       on: ceph.component_collection_status
    class: Errors
     type: Storage
component: Ceph
     calc: $health_collection_failed + $osd_collection_failed + $pool_collection_failed
    units: failed components
    every: 10s
     warn: $this > 0
 summary: One or more Ceph metric components for cluster ${label:fsid} are failing
    info: Health, OSD, or pool collection is failing while other Ceph metrics continue to be collected
      to: sysadmin

# Low Ceph disk availability.

 template: ceph_cluster_physical_capacity_utilization
       on: ceph.cluster_physical_capacity_utilization
    class: Utilization
     type: Storage
component: Ceph
     calc: $utilization
    units: %
    every: 1m
    warn: $this > (($status >= $WARNING ) ? (85) : (90))
    crit: $this > (($status == $CRITICAL) ? (90) : (98))
   delay: down 5m multiplier 1.2 max 1h
 summary: Ceph cluster ${label:fsid} disk space utilization
    info: Ceph cluster ${label:fsid} disk space utilization
      to: sysadmin
