
# database transaction log utilization

 template: mssql_database_log_percent_used
       on: mssql.database_log_percent_used
    class: Utilization
     type: Database
component: Microsoft SQL Server
   lookup: min -15m unaligned of used
    units: %
    every: 1m
     warn: $this > 90
    delay: down 5m multiplier 1.5 max 1h
  summary: SQL Server database ${label:database} transaction log utilization
     info: SQL Server transaction log percent used has been above 90% for the last 15 minutes
       to: dba
