# you can disable an alarm notification by setting the 'to' line to: silent

template: nagios_job_execution_state_warn
      on: nagios.job.execution_state
   class: Errors
    type: Other
component: Nagios
    calc: $warning
   units: state
   every: 10s
    warn: $this != nan AND $this == 1
   delay: down 1m multiplier 1.5 max 1h
 summary: Nagios job ${label:nagios_job} execution state
    info: Nagios job ${label:nagios_job} is in WARNING state
      to: sysadmin

template: nagios_job_execution_state_crit
      on: nagios.job.execution_state
   class: Errors
    type: Other
component: Nagios
    calc: $critical
   units: state
   every: 10s
    crit: $this != nan AND $this == 1
   delay: down 1m multiplier 1.5 max 1h
 summary: Nagios job ${label:nagios_job} execution state
    info: Nagios job ${label:nagios_job} is in CRITICAL state
      to: sysadmin

template: nagios_job_perfdata_threshold_state_warn
      on: nagios.job.perfdata_threshold_state
   class: Errors
    type: Other
component: Nagios
    calc: $warning
   units: state
   every: 10s
    warn: $this != nan AND $this == 1
   delay: down 1m multiplier 1.5 max 1h
 summary: Nagios job ${label:nagios_job} perfdata ${label:perfdata_value} threshold state
    info: Nagios job ${label:nagios_job} perfdata ${label:perfdata_value} is in WARNING threshold state
      to: sysadmin

template: nagios_job_perfdata_threshold_state_crit
      on: nagios.job.perfdata_threshold_state
   class: Errors
    type: Other
component: Nagios
    calc: $critical
   units: state
   every: 10s
    crit: $this != nan AND $this == 1
   delay: down 1m multiplier 1.5 max 1h
 summary: Nagios job ${label:nagios_job} perfdata ${label:perfdata_value} threshold state
    info: Nagios job ${label:nagios_job} perfdata ${label:perfdata_value} is in CRITICAL threshold state
      to: sysadmin
