# you can disable an alarm notification by setting the 'to' line to: silent

    template: runit_service_failed_state
          on: runit.service_state
       class: Errors
        type: Linux
   component: Runit
        calc: $failed
       units: state
       every: 10s
        crit: $this != nan AND $this == 1
       delay: down 5m multiplier 1.5 max 1h
     summary: runit service ${label:service_name} state
        info: runit service in the failed state (should be running but is not)
          to: sysadmin

    template: runit_service_undesired_running
          on: runit.service_state
       class: Errors
        type: Linux
   component: Runit
        calc: $running - $enabled
       units: state
       every: 10s
        warn: $this != nan AND $this == 1
       delay: down 5m multiplier 1.5 max 1h
     summary: runit service ${label:service_name} state
        info: runit service is running but should be down (normally down)
          to: sysadmin

    template: runit_service_paused_state
          on: runit.service_state
       class: Errors
        type: Linux
   component: Runit
        calc: $paused
       units: state
       every: 10s
        warn: $this != nan AND $this == 1
       delay: down 5m multiplier 1.5 max 1h
     summary: runit service ${label:service_name} state
        info: runit service is paused
          to: sysadmin

    template: runit_service_stuck_transitioning
          on: runit.service_state
       class: Latency
        type: Linux
   component: Runit
      lookup: sum -60s unaligned of starting,stopping
       units: state
       every: 10s
        crit: $this != nan AND $this > 30
       delay: down 1m multiplier 1.5 max 1h
     summary: runit service ${label:service_name} state
        info: runit service stuck in transitioning state (starting or stopping)
          to: sysadmin
