
# you can disable an alarm notification by setting the 'to' line to: silent

# -----------------------------------------------Virtual Machine--------------------------------------------------------

 template: vsphere_vm_cpu_utilization
       on: vsphere.vm_cpu_utilization
    class: Utilization
     type: Virtual Machine
component: CPU
   lookup: average -10m unaligned match-names of used
    units: %
    every: 20s
     warn: $this > (($status >= $WARNING)  ? (75) : (85))
     crit: $this > (($status == $CRITICAL) ? (85) : (95))
    delay: down 15m multiplier 1.5 max 1h
  summary: vSphere CPU utilization for VM ${label:vm}
     info: CPU utilization VM ${label:vm} host ${label:host} cluster ${label:cluster} datacenter ${label:datacenter}
       to: silent

 template: vsphere_vm_mem_utilization
       on: vsphere.vm_mem_utilization
    class: Utilization
     type: Virtual Machine
component: Memory
     calc: $used
    units: %
    every: 20s
     warn: $this > (($status >= $WARNING)  ? (80) : (90))
     crit: $this > (($status == $CRITICAL) ? (90) : (98))
    delay: down 15m multiplier 1.5 max 1h
  summary: vSphere memory utilization for VM ${label:vm}
     info: Memory utilization VM ${label:vm} host ${label:host} cluster ${label:cluster} datacenter ${label:datacenter}
       to: silent

 template: vsphere_vm_snapshot_chain_depth
       on: vsphere.vm_snapshot_max_chain_depth
    class: Errors
     type: Virtual Machine
component: Storage
     calc: $depth
    units: snapshots
    every: 20s
     warn: $this > 3
    delay: down 15m multiplier 1.5 max 1h
  summary: vSphere snapshot chain depth for VM ${label:vm}
     info: Snapshot max chain depth for VM ${label:vm} host ${label:host} cluster ${label:cluster} datacenter ${label:datacenter}; zero means no snapshots
       to: sysadmin

 template: vsphere_vm_snapshot_age
       on: vsphere.vm_snapshot_max_age
    class: Errors
     type: Virtual Machine
component: Storage
     calc: $age
    units: seconds
    every: 20s
     crit: $this > 86400
    delay: down 15m multiplier 1.5 max 1h
  summary: vSphere oldest snapshot age for VM ${label:vm}
     info: Oldest snapshot age for VM ${label:vm} host ${label:host} cluster ${label:cluster} datacenter ${label:datacenter}; zero means no snapshots
       to: sysadmin

# -----------------------------------------------ESXI host--------------------------------------------------------------

 template: vsphere_host_cpu_utilization
       on: vsphere.host_cpu_utilization
    class: Utilization
     type: System
component: CPU
   lookup: average -10m unaligned match-names of used
    units: %
    every: 20s
     warn: $this > (($status >= $WARNING)  ? (75) : (85))
     crit: $this > (($status == $CRITICAL) ? (85) : (95))
    delay: down 15m multiplier 1.5 max 1h
  summary: vSphere ESXi CPU utilization for host ${label:host}
     info: CPU utilization ESXi host ${label:host} cluster ${label:cluster} datacenter ${label:datacenter}
       to: sysadmin

 template: vsphere_host_mem_utilization
       on: vsphere.host_mem_utilization
    class: Utilization
     type: System
component: Memory
     calc: $used
    units: %
    every: 20s
     warn: $this > (($status >= $WARNING)  ? (80) : (90))
     crit: $this > (($status == $CRITICAL) ? (90) : (98))
    delay: down 15m multiplier 1.5 max 1h
  summary: vSphere ESXi memory utilization for host ${label:host}
     info: Memory utilization ESXi host ${label:host} cluster ${label:cluster} datacenter ${label:datacenter}
       to: sysadmin
