#!/bin/sh

set -e

case "$1" in
  configure|reconfigure)
    grep /usr/libexec/netdata /var/lib/dpkg/info/netdata-plugin-chartsd.list | xargs -n 30 chown root:netdata
    @ND_APPLY_PERMISSIONS@
    ;;
esac

exit 0
