# The `ebpf type format` option selects the eBPF object file family:
#  `auto`  : The eBPF collector will investigate the hardware and select
#            between the two options below.
#  `legacy`: The eBPF collector will load the legacy (kprobe-based) code.
#            Note: This has a higher overhead.
#  `co-re` : The eBPF collector will use the latest tracing method.
#            Note: This is not available on all platforms.
#
# Uncomment lines to define specific options for the dns thread.
[global]
#    update every = 10
    ebpf type format = auto
