# The `ebpf type format` option selects the eBPF object file family:
#  `auto`  : The eBPF collector will investigate the hardware and select
#            between the two options below.
#  `legacy`: The eBPF collector will load the legacy (kprobe-based) code.
#            Note: This has a higher overhead.
#  `co-re` : The eBPF collector will use the latest tracing method.
#            Note: This is not available on all platforms.
#
# The `ebpf co-re tracing` option selects the CO-RE tracing method:
#   `trampoline`: This is the default mode used by the eBPF collector, due
#                 the small overhead added to host.
#   `probe`     : This is the same as legacy code.
#
# The `maps per core` defines if hash tables will be per core or not.
# This option is ignored on kernels older than 4.6.
#
# Uncomment lines to define specific options for the socket thread.
[global]
#    update every = 10
#    maps per core = yes
    ebpf type format = auto
    ebpf co-re tracing = trampoline
