//! The chart traits (`ChartDimensions`, `NetdataChart`, `InstancedChart`) and the
//! schemars-annotation extraction behind `NetdataChart::chart_metadata`.
//!
//! Two sides consume the `x-chart-*` / `x-dimension-*` annotations: the
//! `NetdataChart` derive macro (`netdata-plugin-charts-derive`) generates a
//! [`ChartDimensions`] impl — one `SET` per named field, skipping
//! `x-chart-instance` fields — while `extract_chart_metadata` reads the same
//! annotations out of the generated JSON schema to build the chart's
//! [`ChartMetadata`]. Both use the struct field name as the dimension id, so the
//! two must stay in sync.

use super::metadata::{ChartMetadata, ChartType, DimensionAlgorithm, DimensionMetadata};
use super::writer::ChartWriter;
use schemars::{JsonSchema, schema_for};
use serde_json::Value;

/// Writes a chart update's dimension values to a [`ChartWriter`].
///
/// Generated by `#[derive(NetdataChart)]` (macro in
/// `netdata-plugin-charts-derive`) or written by hand. The generated impl emits
/// one [`ChartWriter::write_dimension`] per named field, with the field name as
/// the dimension id and the value cast to `i64` — fields must be castable to
/// `i64`. Fields annotated `x-chart-instance` are never written, even when
/// `extract_chart_metadata` keeps them as dimensions. The macro ignores
/// `x-dimension-hidden`: a hidden field still emits a `SET` while
/// `extract_chart_metadata` gives it no `DIMENSION` line.
pub trait ChartDimensions {
    /// Emit one `SET` per dimension between `begin_chart` and `end_chart` (see
    /// `TrackedChart::emit_update`); ids must match the `DIMENSION` definitions
    /// emitted from the chart's [`ChartMetadata`].
    fn write_dimensions(&self, writer: &mut ChartWriter);
}

/// A type published as a Netdata chart.
///
/// A chart type is an ordinary struct: derive `JsonSchema`, put the chart's
/// metadata into schemars `extend(...)` annotations, and derive `NetdataChart`.
/// The derive generates the [`ChartDimensions`] impl; the blanket impl below
/// provides `NetdataChart` itself, and `chart_metadata()` turns the annotations
/// into a [`ChartMetadata`].
///
/// Chart-level annotations (on the struct):
/// - `x-chart-id` — a missing id falls back to `"unknown"`
/// - `x-chart-name`, `x-chart-title`, `x-chart-units`, `x-chart-family`,
///   `x-chart-context`
/// - `x-chart-type` — `line`, `area`, or `stacked` (anything else is `line`)
/// - `x-chart-priority` (i64), `x-chart-update-every` (u64, seconds)
///
/// Dimension-level annotations (on fields):
/// - `x-chart-instance` (bool) — marks the [`InstancedChart`] instance field;
///   excluded from the generated `SET` writes and, by default, from the chart's
///   dimensions
/// - `x-dimension-name`, `x-dimension-multiplier`, `x-dimension-divisor` (i64)
/// - `x-dimension-algorithm` — `absolute`, `incremental`,
///   `percentage-of-absolute-row`, or `percentage-of-incremental-row` (anything
///   else is `absolute`)
/// - `x-dimension-hidden` (bool) — drops the field from the chart's dimensions
///   entirely (no `DIMENSION` line at all, not even a hidden one)
///
/// Every other struct field becomes a dimension, keyed by field name.
///
/// # Example
///
/// ```ignore
/// use rt::NetdataChart;
/// use schemars::JsonSchema;
///
/// #[derive(JsonSchema, NetdataChart, Default, Clone, PartialEq)]
/// #[schemars(
///     extend("x-chart-id" = "system.cpu"),
///     extend("x-chart-title" = "CPU Usage"),
///     extend("x-chart-units" = "percentage"),
/// )]
/// struct CpuMetrics {
///     user: u64,
///     system: u64,
///     idle: u64,
/// }
/// ```
pub trait NetdataChart: JsonSchema + ChartDimensions {
    /// Build this chart's [`ChartMetadata`] from its schema annotations (see
    /// `extract_chart_metadata`).
    fn chart_metadata() -> ChartMetadata {
        let root_schema = schema_for!(Self);
        extract_chart_metadata(&root_schema)
    }
}

/// Blanket impl: any `JsonSchema + ChartDimensions` type is a `NetdataChart`, so
/// the derive macro only has to generate the `ChartDimensions` impl.
impl<T: JsonSchema + ChartDimensions> NetdataChart for T {}

/// A chart template published per instance (e.g. per-CPU, per-disk).
///
/// The chart id contains an `{instance}` placeholder; name, title, family and
/// context may too. Registration does not fan out: the registry instantiates the
/// metadata once from the initial value's `instance_id()`
/// (`TrackedChart::new_instanced` → [`ChartMetadata::instantiate`]), so each
/// concrete instance needs its own registration with its own instance id. An id
/// without `{instance}` gives every registration the same chart id. The instance
/// field itself must be annotated `x-chart-instance` so the generated
/// [`ChartDimensions`] impl skips it.
pub trait InstancedChart: NetdataChart + Clone {
    /// The instance identifier of this value, substituted for `{instance}` in the
    /// chart metadata at registration time.
    fn instance_id(&self) -> &str;

    /// Set the instance identifier. The chart machinery never calls this: set it
    /// on each value before registering that value.
    fn set_instance_id(&mut self, id: &str);
}

/// Build [`ChartMetadata`] from a schemars JSON schema.
///
/// `schema` is a `schema_for!(Self)` root schema: it is serialized to JSON, the
/// `x-chart-*` extensions are read from the root object and the `x-dimension-*`
/// ones from each `properties` entry. Missing annotations keep the
/// [`ChartMetadata::new`] defaults, except that title and context fall back to
/// the chart id; a schema that does not serialize to an object, or a missing
/// `x-chart-id`, yields the id `"unknown"`.
fn extract_chart_metadata<T: serde::Serialize>(schema: &T) -> ChartMetadata {
    let schema_value = serde_json::to_value(schema).unwrap_or(Value::Null);
    let Some(obj) = schema_value.as_object() else {
        return ChartMetadata::new("unknown");
    };

    let mut metadata = ChartMetadata::new(
        extract_string_from_json(obj, "x-chart-id").unwrap_or_else(|| "unknown".to_string()),
    );

    if let Some(name) = extract_string_from_json(obj, "x-chart-name") {
        metadata.name = name;
    }

    if let Some(title) = extract_string_from_json(obj, "x-chart-title") {
        metadata.title = title;
    }

    if let Some(units) = extract_string_from_json(obj, "x-chart-units") {
        metadata.units = units;
    }

    if let Some(family) = extract_string_from_json(obj, "x-chart-family") {
        metadata.family = family;
    }

    if let Some(context) = extract_string_from_json(obj, "x-chart-context") {
        metadata.context = context;
    }

    if let Some(chart_type) = extract_string_from_json(obj, "x-chart-type") {
        metadata.chart_type = match chart_type.as_str() {
            "line" => ChartType::Line,
            "area" => ChartType::Area,
            "stacked" => ChartType::Stacked,
            _ => ChartType::Line,
        };
    }

    if let Some(priority) = extract_i64_from_json(obj, "x-chart-priority") {
        metadata.priority = priority;
    }

    if let Some(update_every) = extract_u64_from_json(obj, "x-chart-update-every") {
        metadata.update_every = update_every;
    }

    if let Some(properties) = obj.get("properties").and_then(|v| v.as_object()) {
        for (field_name, field_schema) in properties {
            if let Some(field_obj) = field_schema.as_object() {
                if extract_bool_from_json(field_obj, "x-chart-instance").unwrap_or(false) {
                    metadata.instance_field = Some(field_name.clone());

                    // Instance fields are excluded from dimensions by default; keep one
                    // only with an explicit x-dimension-hidden = false.
                    if !extract_bool_from_json(field_obj, "x-dimension-hidden").unwrap_or(true) {
                        let dim = extract_dimension_metadata(field_name, field_obj);
                        metadata.dimensions.insert(field_name.clone(), dim);
                    }
                    continue;
                }

                // Hidden fields are dropped from the chart entirely: no DIMENSION
                // line at all, not even a hidden one.
                if extract_bool_from_json(field_obj, "x-dimension-hidden").unwrap_or(false) {
                    continue;
                }

                let dim = extract_dimension_metadata(field_name, field_obj);
                metadata.dimensions.insert(field_name.clone(), dim);
            }
        }
    }

    metadata
}

/// Build one [`DimensionMetadata`] from a field's schema object.
///
/// Defaults come from [`DimensionMetadata::new`] (id and name are the field
/// name, algorithm `absolute`, multiplier/divisor 1); the `x-dimension-*`
/// annotations override them, and an unrecognized `x-dimension-algorithm` falls
/// back to `absolute`. The id stays the field name, so it always matches what
/// [`ChartDimensions::write_dimensions`] emits. Callers pre-filter
/// `x-dimension-hidden`, so `hidden` stays false here.
fn extract_dimension_metadata(
    field_name: &str,
    field_obj: &serde_json::Map<String, Value>,
) -> DimensionMetadata {
    let mut dim = DimensionMetadata::new(field_name);

    if let Some(name) = extract_string_from_json(field_obj, "x-dimension-name") {
        dim.name = name;
    }

    if let Some(algorithm) = extract_string_from_json(field_obj, "x-dimension-algorithm") {
        dim.algorithm = match algorithm.as_str() {
            "absolute" => DimensionAlgorithm::Absolute,
            "incremental" => DimensionAlgorithm::Incremental,
            "percentage-of-absolute-row" => DimensionAlgorithm::PercentageOfAbsoluteRow,
            "percentage-of-incremental-row" => DimensionAlgorithm::PercentageOfIncrementalRow,
            _ => DimensionAlgorithm::Absolute,
        };
    }

    if let Some(multiplier) = extract_i64_from_json(field_obj, "x-dimension-multiplier") {
        dim.multiplier = multiplier;
    }

    if let Some(divisor) = extract_i64_from_json(field_obj, "x-dimension-divisor") {
        dim.divisor = divisor;
    }

    if extract_bool_from_json(field_obj, "x-dimension-hidden").unwrap_or(false) {
        dim.hidden = true;
    }

    dim
}

/// `obj[key]` as a `String`, or `None` when the key is missing or not a string.
fn extract_string_from_json(obj: &serde_json::Map<String, Value>, key: &str) -> Option<String> {
    obj.get(key).and_then(|v| v.as_str()).map(|s| s.to_string())
}

/// `obj[key]` as an `i64`, or `None` when the key is missing or not an integer.
fn extract_i64_from_json(obj: &serde_json::Map<String, Value>, key: &str) -> Option<i64> {
    obj.get(key).and_then(|v| match v {
        Value::Number(n) => n.as_i64(),
        _ => None,
    })
}

/// `obj[key]` as a `u64`, or `None` when the key is missing or not an integer.
fn extract_u64_from_json(obj: &serde_json::Map<String, Value>, key: &str) -> Option<u64> {
    obj.get(key).and_then(|v| match v {
        Value::Number(n) => n.as_u64(),
        _ => None,
    })
}

/// `obj[key]` as a `bool`, or `None` when the key is missing or not a boolean.
fn extract_bool_from_json(obj: &serde_json::Map<String, Value>, key: &str) -> Option<bool> {
    obj.get(key).and_then(|v| v.as_bool())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(JsonSchema, Default, Clone, PartialEq)]
    #[schemars(
        extend("x-chart-id" = "test.chart"),
        extend("x-chart-title" = "Test Chart"),
        extend("x-chart-units" = "widgets"),
        extend("x-chart-type" = "stacked")
    )]
    struct TestMetrics {
        value1: u64,
        value2: u64,
    }

    impl ChartDimensions for TestMetrics {
        fn write_dimensions(&self, writer: &mut crate::charts::writer::ChartWriter) {
            writer.write_dimension("value1", self.value1 as i64);
            writer.write_dimension("value2", self.value2 as i64);
        }
    }

    #[test]
    fn test_extract_metadata() {
        let metadata = TestMetrics::chart_metadata();
        assert_eq!(metadata.id, "test.chart");
        assert_eq!(metadata.title, "Test Chart");
        assert_eq!(metadata.units, "widgets");
        assert_eq!(metadata.chart_type, ChartType::Stacked);
        assert_eq!(metadata.dimensions.len(), 2);
        assert!(metadata.dimensions.contains_key("value1"));
        assert!(metadata.dimensions.contains_key("value2"));
    }
}
