#!/bin/sh

set -e

case "$1" in
  remove) ;;

  purge)
    if dpkg-statoverride --list | grep -qw /var/cache/netdata; then
      dpkg-statoverride --remove /var/cache/netdata
    fi

    if dpkg-statoverride --list | grep -qw /var/lib/netdata/www; then
      dpkg-statoverride --remove /var/lib/netdata/www
    fi

    if dpkg-statoverride --list | grep -qw /usr/share/netdata/www; then
      dpkg-statoverride --remove /usr/share/netdata/www
    fi

    if dpkg-statoverride --list | grep -qw /var/lib/netdata/registry; then
      dpkg-statoverride --remove /var/lib/netdata/registry
    fi

    if dpkg-statoverride --list | grep -qw /var/lib/netdata; then
      dpkg-statoverride --remove /var/lib/netdata
    fi

    if dpkg-statoverride --list | grep -qw /var/run/netdata; then
      dpkg-statoverride --remove /var/run/netdata
    fi

    if dpkg-statoverride --list | grep -qw /var/log/netdata; then
      dpkg-statoverride --remove /var/log/netdata
    fi
    ;;

  *) ;;

esac

#DEBHELPER#

exit 0
