#!/bin/sh

set -e

case "$1" in
  configure|reconfigure)
    chown root:netdata /usr/libexec/netdata/plugins.d/ibm.d.plugin
    chmod 0750 /usr/libexec/netdata/plugins.d/ibm.d.plugin
    # IBM plugin doesn't need special capabilities
    ;;
esac

exit 0