// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Prefix {
    #[prost(message, optional, tag = "1")]
    pub address: ::core::option::Option<Ip>,
    #[prost(uint32, tag = "2")]
    pub length: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ip {
    #[prost(uint64, tag = "1")]
    pub higher: u64,
    #[prost(uint64, tag = "2")]
    pub lower: u64,
    #[prost(enumeration = "ip::Version", tag = "3")]
    pub version: i32,
}
/// Nested message and enum types in `IP`.
pub mod ip {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Version {
        Unspecified = 0,
        IPv4 = 1,
        IPv6 = 2,
    }
    impl Version {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "VERSION_UNSPECIFIED",
                Self::IPv4 => "IPv4",
                Self::IPv6 => "IPv6",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "VERSION_UNSPECIFIED" => Some(Self::Unspecified),
                "IPv4" => Some(Self::IPv4),
                "IPv6" => Some(Self::IPv6),
                _ => None,
            }
        }
    }
}
