// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Route {
    #[prost(message, optional, tag = "1")]
    pub pfx: ::core::option::Option<super::net::Prefix>,
    #[prost(message, repeated, tag = "2")]
    pub paths: ::prost::alloc::vec::Vec<Path>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Path {
    #[prost(enumeration = "path::Type", tag = "1")]
    pub r#type: i32,
    #[prost(message, optional, tag = "2")]
    pub static_path: ::core::option::Option<StaticPath>,
    #[prost(message, optional, tag = "3")]
    pub bgp_path: ::core::option::Option<BgpPath>,
    #[prost(enumeration = "path::HiddenReason", tag = "4")]
    pub hidden_reason: i32,
    #[prost(uint32, tag = "5")]
    pub time_learned: u32,
    #[prost(message, optional, tag = "6")]
    pub grp_path: ::core::option::Option<GrpPath>,
}
/// Nested message and enum types in `Path`.
pub mod path {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Type {
        Static = 0,
        Bgp = 1,
        Grp = 2,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Static => "Static",
                Self::Bgp => "BGP",
                Self::Grp => "GRP",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "Static" => Some(Self::Static),
                "BGP" => Some(Self::Bgp),
                "GRP" => Some(Self::Grp),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum HiddenReason {
        None = 0,
        NextHopUnreachable = 1,
        FilteredByPolicy = 2,
        AsLoop = 3,
        OurOriginatorId = 4,
        ClusterLoop = 5,
        OtcMismatch = 6,
    }
    impl HiddenReason {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::None => "HiddenReasonNone",
                Self::NextHopUnreachable => "HiddenReasonNextHopUnreachable",
                Self::FilteredByPolicy => "HiddenReasonFilteredByPolicy",
                Self::AsLoop => "HiddenReasonASLoop",
                Self::OurOriginatorId => "HiddenReasonOurOriginatorID",
                Self::ClusterLoop => "HiddenReasonClusterLoop",
                Self::OtcMismatch => "HiddenReasonOTCMismatch",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "HiddenReasonNone" => Some(Self::None),
                "HiddenReasonNextHopUnreachable" => Some(Self::NextHopUnreachable),
                "HiddenReasonFilteredByPolicy" => Some(Self::FilteredByPolicy),
                "HiddenReasonASLoop" => Some(Self::AsLoop),
                "HiddenReasonOurOriginatorID" => Some(Self::OurOriginatorId),
                "HiddenReasonClusterLoop" => Some(Self::ClusterLoop),
                "HiddenReasonOTCMismatch" => Some(Self::OtcMismatch),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StaticPath {
    #[prost(message, optional, tag = "1")]
    pub next_hop: ::core::option::Option<super::net::Ip>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GrpPath {
    #[prost(message, optional, tag = "1")]
    pub next_hop: ::core::option::Option<super::net::Ip>,
    #[prost(map = "string, string", tag = "2")]
    pub meta_data: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BgpPath {
    #[prost(uint32, tag = "1")]
    pub path_identifier: u32,
    #[prost(message, optional, tag = "2")]
    pub next_hop: ::core::option::Option<super::net::Ip>,
    #[prost(uint32, tag = "3")]
    pub local_pref: u32,
    #[prost(message, repeated, tag = "4")]
    pub as_path: ::prost::alloc::vec::Vec<AsPathSegment>,
    #[prost(uint32, tag = "5")]
    pub origin: u32,
    #[prost(uint32, tag = "6")]
    pub med: u32,
    #[prost(bool, tag = "7")]
    pub ebgp: bool,
    #[prost(uint32, tag = "8")]
    pub bgp_identifier: u32,
    #[prost(message, optional, tag = "9")]
    pub source: ::core::option::Option<super::net::Ip>,
    #[prost(uint32, repeated, tag = "10")]
    pub communities: ::prost::alloc::vec::Vec<u32>,
    #[prost(message, repeated, tag = "11")]
    pub large_communities: ::prost::alloc::vec::Vec<LargeCommunity>,
    #[prost(uint32, tag = "12")]
    pub originator_id: u32,
    #[prost(uint32, repeated, tag = "13")]
    pub cluster_list: ::prost::alloc::vec::Vec<u32>,
    #[prost(message, repeated, tag = "14")]
    pub unknown_attributes: ::prost::alloc::vec::Vec<UnknownPathAttribute>,
    #[prost(bool, tag = "15")]
    pub bmp_post_policy: bool,
    #[prost(uint32, tag = "16")]
    pub only_to_customer: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AsPathSegment {
    #[prost(bool, tag = "1")]
    pub as_sequence: bool,
    #[prost(uint32, repeated, tag = "2")]
    pub asns: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LargeCommunity {
    #[prost(uint32, tag = "1")]
    pub global_administrator: u32,
    #[prost(uint32, tag = "2")]
    pub data_part1: u32,
    #[prost(uint32, tag = "3")]
    pub data_part2: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnknownPathAttribute {
    #[prost(bool, tag = "1")]
    pub optional: bool,
    #[prost(bool, tag = "2")]
    pub transitive: bool,
    #[prost(bool, tag = "3")]
    pub partial: bool,
    #[prost(uint32, tag = "4")]
    pub type_code: u32,
    #[prost(bytes = "vec", tag = "5")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
