/* Generated by re2c 3.0 on Tue Dec  3 14:14:31 2024 */
#line 1 "re2c_line_splitter.re.c"
#line 4 "re2c_line_splitter.c"
#define YYMAXFILL 2
#line 1 "re2c_line_splitter.re.c"


#include <stddef.h>

size_t quoted_strings_splitter_pluginsd_re2c(char *start, char **words, size_t max_words)
{
    size_t count = 0;
    char *YYMARKER = NULL;

    char *YYCURSOR = start;
    for (;;) {
    
#line 19 "re2c_line_splitter.c"
{
	char yych;
	static const unsigned char yybm[] = {
		  0, 208, 208, 208, 208, 208, 208, 208, 
		208, 224, 224, 224, 224, 224, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		224, 208, 128, 208, 208, 208, 208,  64, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 224, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
	};
	yych = *YYCURSOR;
	if (yybm[0+yych] & 16) {
		goto yy2;
	}
	if (yych <= 0x00) goto yy1;
	if (yych <= ' ') goto yy3;
	if (yych <= '"') goto yy4;
	if (yych <= '\'') goto yy6;
	goto yy3;
yy1:
	++YYCURSOR;
#line 26 "re2c_line_splitter.re.c"
	{
            if (count < max_words)
                words[count] = NULL;

            return count;
        }
#line 74 "re2c_line_splitter.c"
yy2:
	yych = *++YYCURSOR;
	if (yybm[0+yych] & 16) {
		goto yy2;
	}
#line 41 "re2c_line_splitter.re.c"
	{
            if (count == max_words)
                return count;

            if (*YYCURSOR != '\0')
                *YYCURSOR++ = '\0';

            words[count++] = start;
            start = YYCURSOR;
            continue;
        }
#line 92 "re2c_line_splitter.c"
yy3:
	yych = *++YYCURSOR;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 52 "re2c_line_splitter.re.c"
	{
            start = (char *) YYCURSOR;
            continue;
        }
#line 103 "re2c_line_splitter.c"
yy4:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych >= 0x01) goto yy8;
yy5:
#line 21 "re2c_line_splitter.re.c"
	{
            if (count < max_words)
                words[count] = NULL;
            return count;
        }
#line 114 "re2c_line_splitter.c"
yy6:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x00) goto yy5;
	goto yy12;
yy7:
	yych = *++YYCURSOR;
yy8:
	if (yybm[0+yych] & 64) {
		goto yy7;
	}
	if (yych >= 0x01) goto yy10;
yy9:
	YYCURSOR = YYMARKER;
	goto yy5;
yy10:
	++YYCURSOR;
#line 32 "re2c_line_splitter.re.c"
	{
            if (count == max_words)
                return count;

            start++;
            start[YYCURSOR - start - 1] = '\0';
            words[count++] = start;
            continue;
        }
#line 141 "re2c_line_splitter.c"
yy11:
	yych = *++YYCURSOR;
yy12:
	if (yybm[0+yych] & 128) {
		goto yy11;
	}
	if (yych <= 0x00) goto yy9;
	goto yy10;
}
#line 56 "re2c_line_splitter.re.c"

    }
}
