/* Generated by re2c 3.0 on Tue Nov 26 12:06:58 2024 */
#line 1 "src/libnetdata/line_splitter/re2c_line_splitter.re.c"
#line 4 "src/libnetdata/line_splitter/re2c_line_splitter.c"
#define YYMAXFILL 1
#line 1 "src/libnetdata/line_splitter/re2c_line_splitter.re.c"


#include <stddef.h>

size_t quoted_strings_splitter_pluginsd_re2c(char *start, char **words, size_t max_words)
{
    size_t count = 0;

    const char *YYCURSOR = start;
    for (;;) {
    
#line 18 "src/libnetdata/line_splitter/re2c_line_splitter.c"
{
	char yych;
	static const unsigned char yybm[] = {
		192, 208, 208, 208, 208, 208, 208, 208, 
		208, 224, 224, 224, 224, 224, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		224, 208, 128, 208, 208, 208, 208,  64, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 224, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
	};
	yych = *YYCURSOR;
	if (yybm[0+yych] & 16) {
		goto yy2;
	}
	if (yych <= 0x00) goto yy1;
	if (yych <= ' ') goto yy3;
	if (yych <= '"') goto yy4;
	if (yych <= '\'') goto yy5;
	goto yy3;
yy1:
	++YYCURSOR;
#line 23 "src/libnetdata/line_splitter/re2c_line_splitter.re.c"
	{
            return count;
        }
#line 70 "src/libnetdata/line_splitter/re2c_line_splitter.c"
yy2:
	yych = *++YYCURSOR;
	if (yybm[0+yych] & 16) {
		goto yy2;
	}
#line 35 "src/libnetdata/line_splitter/re2c_line_splitter.re.c"
	{
            if (count == max_words)
                return count;

            start[YYCURSOR - start] = '\0';
            words[count++] = start;
            start = (char *) ++YYCURSOR;
            continue;
        }
#line 86 "src/libnetdata/line_splitter/re2c_line_splitter.c"
yy3:
	yych = *++YYCURSOR;
	if (yybm[0+yych] & 32) {
		goto yy3;
	}
#line 44 "src/libnetdata/line_splitter/re2c_line_splitter.re.c"
	{
            start = (char *) YYCURSOR;
            continue;
        }
#line 97 "src/libnetdata/line_splitter/re2c_line_splitter.c"
yy4:
	yych = *++YYCURSOR;
	if (yybm[0+yych] & 64) {
		goto yy4;
	}
	goto yy6;
yy5:
	yych = *++YYCURSOR;
	if (yybm[0+yych] & 128) {
		goto yy5;
	}
yy6:
	++YYCURSOR;
#line 26 "src/libnetdata/line_splitter/re2c_line_splitter.re.c"
	{
            if (count == max_words)
                return count;

            start++;
            start[YYCURSOR - start - 1] = '\0';
            words[count++] = start;
            continue;
        }
#line 121 "src/libnetdata/line_splitter/re2c_line_splitter.c"
}
#line 48 "src/libnetdata/line_splitter/re2c_line_splitter.re.c"

    }
}
