
		SELECT
			SERVER_NAME,
			HTTP_FUNCTION,
			SERVER_NORMAL_CONNECTIONS,
			SERVER_SSL_CONNECTIONS,
			SERVER_ACTIVE_THREADS,
			SERVER_IDLE_THREADS,
			SERVER_TOTAL_REQUESTS,
			SERVER_TOTAL_RESPONSES,
			SERVER_TOTAL_REQUESTS_REJECTED,
			REQUESTS,
			RESPONSES,
			NONCACHE_RESPONSES,
			BYTES_RECEIVED,
			BYTES_SENT,
			NONCACHE_PROCESSING_TIME,
			CACHE_PROCESSING_TIME
		FROM QSYS2.HTTP_SERVER_INFO
	