
		SELECT 
			COALESCE(LINE_DESCRIPTION, 'UNKNOWN') as LINE_DESCRIPTION,
			COALESCE(INTERFACE_LINE_TYPE, 'UNKNOWN') as INTERFACE_LINE_TYPE,
			COALESCE(INTERFACE_STATUS, 'UNKNOWN') as INTERFACE_STATUS,
			COALESCE(CONNECTION_TYPE, 'UNKNOWN') as CONNECTION_TYPE,
			COALESCE(INTERNET_ADDRESS, '') as INTERNET_ADDRESS,
			COALESCE(NETWORK_ADDRESS, '') as NETWORK_ADDRESS,
			COALESCE(MAXIMUM_TRANSMISSION_UNIT, 0) as MTU
		FROM QSYS2.NETSTAT_INTERFACE_INFO
		WHERE LINE_DESCRIPTION != '*LOOPBACK'
		ORDER BY LINE_DESCRIPTION
	