
		SELECT 
			UNIT_NUMBER,
			UNIT_TYPE,
			PERCENT_USED,
			UNIT_SPACE_AVAILABLE_GB,
			UNIT_STORAGE_CAPACITY,
			TOTAL_READ_REQUESTS,
			TOTAL_WRITE_REQUESTS,
			TOTAL_BLOCKS_READ,
			TOTAL_BLOCKS_WRITTEN,
			ELAPSED_PERCENT_BUSY,
			COALESCE(SSD_LIFE_REMAINING, -1) as SSD_LIFE_REMAINING,
			COALESCE(SSD_POWER_ON_DAYS, -1) as SSD_POWER_ON_DAYS,
			COALESCE(HARDWARE_STATUS, 'UNKNOWN') as HARDWARE_STATUS,
			COALESCE(DISK_MODEL, 'UNKNOWN') as DISK_MODEL,
			COALESCE(SERIAL_NUMBER, 'UNKNOWN') as SERIAL_NUMBER
		FROM QSYS2.SYSDISKSTAT
	