
		SELECT COUNT(*) AS COUNT
		FROM (
			SELECT
				COALESCE(MESSAGE_QUEUE_LIBRARY, '') AS LIBRARY,
				COALESCE(MESSAGE_QUEUE_NAME, '') AS NAME
			FROM QSYS2.MESSAGE_QUEUE_INFO
			GROUP BY COALESCE(MESSAGE_QUEUE_LIBRARY, ''), COALESCE(MESSAGE_QUEUE_NAME, '')
		) X
	