// SPDX-License-Identifier: GPL-3.0-or-later
//
// Regenerate `nd_promql.h` from the public FFI surface of this crate.
//
// The generated header is committed to the source tree (see SOW-0016).
// `build.rs` writes it idempotently; PR review catches drift.

use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_language(cbindgen::Language::C)
        .with_cpp_compat(true)
        .with_include_guard("ND_PROMQL_H")
        .with_pragma_once(false)
        .with_header(
            "/* SPDX-License-Identifier: GPL-3.0-or-later */\n\
             /* Generated by cbindgen from netdata-promql; do not edit. */",
        )
        .generate()
        .expect("Unable to generate bindings for netdata-promql")
        .write_to_file(format!("{crate_dir}/nd_promql.h"));

    println!("cargo:rerun-if-changed=src/");
    println!("cargo:rerun-if-changed=Cargo.toml");
    println!("cargo:rerun-if-changed=build.rs");
}
