/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Generated by cbindgen from netdata-promql; do not edit. */

#ifndef ND_PROMQL_H
#define ND_PROMQL_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle for a query response.
 */
typedef struct NdPromqlResponse NdPromqlResponse;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Evaluate an instant PromQL query at `at_ms`.
 *
 * # Safety
 * All pointer parameters must be either null or valid NUL-terminated C
 * strings valid for the duration of the call. The returned handle must
 * be released exactly once with `nd_promql_response_free`.
 */
struct NdPromqlResponse *nd_promql_query_instant(const char *host_machine_guid,
                                                 const char *query,
                                                 int64_t at_ms,
                                                 int64_t _timeout_ms);

/**
 * Evaluate a range PromQL query over `[start_ms, end_ms]` at `step_ms`
 * granularity.
 *
 * # Safety
 * Same requirements as `nd_promql_query_instant`.
 */
struct NdPromqlResponse *nd_promql_query_range(const char *host_machine_guid,
                                               const char *query,
                                               int64_t start_ms,
                                               int64_t end_ms,
                                               int64_t step_ms,
                                               int64_t _timeout_ms);

/**
 * Pointer to the NUL-terminated response body.
 */
const char *nd_promql_response_body(const struct NdPromqlResponse *r);

/**
 * Byte length of the response body, excluding the trailing NUL.
 */
uintptr_t nd_promql_response_body_len(const struct NdPromqlResponse *r);

/**
 * HTTP status code that should accompany the response body.
 */
int nd_promql_response_http_status(const struct NdPromqlResponse *r);

/**
 * Release a response handle. Safe to call on null.
 */
void nd_promql_response_free(struct NdPromqlResponse *r);

/**
 * FFI: `/api/v1/labels`. Returns the union of label names across the
 * resolved series.
 *
 * # Safety
 * `matchers` must be NULL or a pointer to `matchers_len` C strings. Each
 * non-NULL string is borrowed for the duration of the call.
 */
struct NdPromqlResponse *nd_promql_labels(const char *host_machine_guid,
                                          const char *const *matchers,
                                          uintptr_t matchers_len,
                                          int64_t start_ms,
                                          int64_t end_ms,
                                          uintptr_t limit);

/**
 * FFI: `/api/v1/label/<name>/values`.
 *
 * Includes a fast path for `__name__`: when the requested label is
 * `__name__` AND no `match[]` selectors were supplied, the call walks
 * `host->rrdctx.contexts` directly via `nd_pds_metric_names_collect`
 * instead of resolving every series on every chart. On a populated host
 * this is roughly an order of magnitude faster (32 ms -> ~3 ms for the
 * Grafana metric-browser fetch).
 *
 * # Safety
 * `label_name` and each non-null pointer in `matchers` must be valid
 * NUL-terminated C strings for the duration of the call.
 */
struct NdPromqlResponse *nd_promql_label_values(const char *host_machine_guid,
                                                const char *label_name,
                                                const char *const *matchers,
                                                uintptr_t matchers_len,
                                                int64_t start_ms,
                                                int64_t end_ms,
                                                uintptr_t limit);

/**
 * FFI: `/api/v1/series`. Returns one label map per unique series.
 *
 * # Safety
 * `matchers` must be NULL or a pointer to `matchers_len` C strings.
 */
struct NdPromqlResponse *nd_promql_series(const char *host_machine_guid,
                                          const char *const *matchers,
                                          uintptr_t matchers_len,
                                          int64_t start_ms,
                                          int64_t end_ms,
                                          uintptr_t limit);

/**
 * FFI: `/api/v1/metadata`. Returns per-metric TYPE/HELP/unit, optionally
 * filtered to a single metric name. `start_ms`/`end_ms` are honored when
 * both non-zero: contexts whose last collection predates the window are
 * skipped.
 *
 * # Safety
 * `metric_filter` must be NULL or a valid NUL-terminated C string.
 */
struct NdPromqlResponse *nd_promql_metadata(const char *host_machine_guid,
                                            const char *metric_filter,
                                            uintptr_t limit,
                                            int64_t start_ms,
                                            int64_t end_ms);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ND_PROMQL_H */
