---
# Upload the updater script to the artifacts hosting
name: Upload Updater Script
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/updater-upload.yml
      - packaging/installer/netdata-updater.sh
  workflow_dispatch: null
concurrency:
  group: updater-upload
  cancel-in-progress: true
jobs:
  upload:
    name: Upload Updater Script
    runs-on: ubuntu-latest
    if: github.repository == 'netdata/netdata' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
      - name: Install Rclone
        id: install-rclone
        run: |
          sudo apt-get update || exit 1
          sudo apt-get install -y rclone || exit 1
      - name: Upload Updater
        id: upload
        env:
          RCLONE_CONFIG_S3_TYPE: "s3"
          RCLONE_CONFIG_S3_PROVIDER: "Cloudflare"
          RCLONE_CONFIG_S3_ACCESS_KEY_ID: "${{ secrets.CLOUDFLARE_R2_ACCESS_KEY }}"
          RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: "${{ secrets.CLOUDFLARE_R2_SECRET_KEY }}"
          RCLONE_CONFIG_S3_ENDPOINT: "${{ secrets.CLOUDFLARE_R2_RELEASE_ENDPOINT }}"
          RCLONE_CONFIG_S3_REGION: "auto"
        run: |
          rclone copyto --verbose --fast-list --use-server-modtime --header-upload "Cache-Control: no-transform" packaging/installer/netdata-updater.sh s3:netdata-agent-artifacts/netdata-updater.sh
      - name: Failure Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: 'danger'
          SLACK_FOOTER: ''
          SLACK_ICON_EMOJI: ':github-actions:'
          SLACK_TITLE: 'Failed to upload updated updater script:'
          SLACK_USERNAME: 'GitHub Actions'
          SLACK_MESSAGE: |-
              ${{ github.repository }}: Failed to upload updated updater script.
              Checkout: ${{ steps.checkout.outcome }}
              Install Rclone: ${{ steps.install-rclone.outcome }}
              Upload updater: ${{ steps.upload.outcome }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ failure() }}
